import assert from "node:assert/strict";
import { mkdir } from "node:fs/promises";
import { createServer } from "vite";
import { chromium } from "../../html-renderer/node_modules/playwright/index.mjs";

const server = await createServer({ server: { host: "127.0.0.1", port: 1597, strictPort: true, hmr: false, watch: null } });
await server.listen();
const browser = await chromium.launch({ channel: "chrome", headless: true });
const page = await browser.newPage({ viewport: { width: 1050, height: 700 } });
const errors = [];
page.on("pageerror", (error) => errors.push(error.message));
const button = (name) => page.getByRole("button", { name, exact: true });
try {
  await page.goto("http://127.0.0.1:1597/scripts/fixtures/app-updater/preview.html");
  await page.evaluate(() => { window.mode = "offline"; });
  await button("检查更新").click();
  await page.getByRole("alert").filter({ hasText: "网络不可用" }).waitFor();
  await page.evaluate(() => { window.mode = "current"; });
  await button("检查更新").click();
  await page.getByText("当前已是最新版本。").waitFor();
  await page.evaluate(() => { window.mode = "available"; });
  await button("检查更新").click();
  await button("下载更新").click();
  await page.getByText(/50%/).waitFor();
  assert.equal(await button("正在下载…").isDisabled(), true);
  await page.evaluate(() => Promise.all([window.updater.getState().download(), window.updater.getState().check()]));
  assert.equal(await page.evaluate(() => window.calls.filter(c => c === "plugin:updater|download").length), 1);
  await button("切换设置").click();
  await button("切换设置").click();
  await page.getByText(/50%/).waitFor();
  await page.evaluate(() => { window.badSignature = true; window.finishDownload(); });
  await page.getByRole("alert").filter({ hasText: "签名校验失败" }).waitFor();
  assert.equal(await button("安装并重启").count(), 0);
  await page.evaluate(() => { window.badSignature = false; window.unknownSize = true; });
  await button("下载更新").click();
  await button("正在下载…").waitFor();
  assert.equal(await page.getByRole("progressbar").getAttribute("value"), null);
  await page.evaluate(() => window.finishDownload());
  await button("安装并重启").waitFor();
  await mkdir(".tmp/app-updater", { recursive: true });
  await page.screenshot({ path: ".tmp/app-updater/ready.png" });
  await page.evaluate(() => window.store.setState({ generating: true }));
  await button("安装并重启").click();
  await page.getByRole("alert").filter({ hasText: "正在进行" }).waitFor();
  assert.equal(await page.evaluate(() => window.calls.includes("plugin:updater|install")), false);
  await page.evaluate(() => { window.store.setState({ generating: false }); window.flushFails = true; });
  await button("安装并重启").click();
  await page.getByRole("alert").filter({ hasText: "保存失败" }).waitFor();
  assert.equal(await page.evaluate(() => window.calls.includes("plugin:updater|install")), false);
  await page.evaluate(() => { window.flushFails = false; window.installFails = true; });
  await button("安装并重启").click();
  await page.getByRole("alert").filter({ hasText: "安装程序启动失败" }).waitFor();
  await page.evaluate(() => { window.installFails = false; window.restartFails = true; });
  await button("安装并重启").click();
  await page.getByRole("alert").filter({ hasText: "更新已安装" }).waitFor();
  await button("重启应用").click();
  const calls = await page.evaluate(() => window.calls);
  assert.ok(calls.indexOf("flush") < calls.indexOf("plugin:updater|install"));
  assert.equal(calls.filter(c => c === "plugin:updater|install").length, 2, "restart retries never install again");
  assert.deepEqual(errors, []);
  console.log("PASS updater: offline/current/new release, progress, reopen, duplicate calls, invalid signature, retry, task/save guards, install/restart failures");
} finally { await browser.close(); await server.close(); }
