import assert from 'node:assert/strict';
import { mkdir } from 'node:fs/promises';
import { createServer } from 'vite';
import { chromium } from '../../html-renderer/node_modules/playwright/index.mjs';
const server=await createServer({configFile:false,root:process.cwd(),server:{host:'127.0.0.1',port:1592,strictPort:true,hmr:false,watch:null}});
await server.listen();
const browser=await chromium.launch({channel:'chrome',headless:true});
const page=await browser.newPage({viewport:{width:1800,height:1200}});
const errors=[];page.on('pageerror',error=>errors.push(error.message));
try {
  await page.goto('http://127.0.0.1:1592/scripts/fixtures/canvas-reference/preview.html');
  await page.locator('[data-canvas-node-id="old"]').waitFor();
  await page.evaluate(async()=>{
    const {api}=await import('/src/lib/api.ts');
    const {CanvasWorkflowController}=await import('/src/lib/canvasWorkflowRuntime.ts');
    const {newWorkflowNode}=await import('/src/lib/canvasWorkflow.ts');
    const {useStore}=await import('/src/store.ts');
    const check=(v,m)=>{if(!v)throw new Error(m);};
    const node=id=>({...newWorkflowNode('generation',0,0,'codex'),id,prompt:id});
    const source=node('source'),target=id=>({...node(id),prompt:'use @[result]',inputs:{image:[{nodeId:'source',portId:'image'}]},promptReferences:[{id:'result',type:'image',input:{nodeId:'source',portId:'image'},label:'本次生成图片'}]});
    const c=new CanvasWorkflowController('image-chain');await c.load();await c.edit([source,target('target'),target('branch')]);
    let round=1,fail=false,release,started,delay=true;const calls=[];
    let signal=new Promise(resolve=>{started=resolve;});
    api.localAgentFindAssetId=async path=>path.replace('.png','');
    useStore.setState({startGeneration:async(...args)=>{
      const identity=args[12],isSource=args[0]==='source';calls.push({source:isSource,assets:args[1].map(a=>a.id),identity});
      if(isSource&&delay){started();await new Promise(resolve=>{release=resolve;});}
      if(isSource&&fail)throw new Error('source failed');
      const images=isSource?(round===1?['a.png','b.png']:['c.png','d.png']):['existing.png'];
      useStore.setState(s=>({genJobs:{...s.genJobs,[identity.jobId]:{turns:[{turnKey:identity.turnKey,images},{turnKey:'manual-later',images:['wrong.png']}]} }}));
      return {accepted:true};
    }});
    const running=c.start('source');await signal;
    check(calls.length===1,'downstream waits for upstream completion');
    const firstSession=c.document.nodes[0].activeSessionNodeId;
    check(firstSession&&c.document.nodes[0].outputs.image===undefined,'new session binds before provider completes');
    release();await running;
    check(c.document.run.status==='done'&&calls.length===3,'chain and fanout complete');
    check(calls.slice(1).every(call=>call.assets.join(',')==='a,b'),'both branches consume only this turn images');
    round=2;signal=new Promise(resolve=>{started=resolve;});
    const rerun=c.start('source');await signal;
    const secondSession=c.document.nodes[0].activeSessionNodeId;
    check(secondSession!==firstSession&&c.document.nodes[0].sessionNodeIds.includes(firstSession),'rerun replaces current session but keeps history');
    check(!c.document.nodes[0].outputs.image&&calls.length===4,'old images unavailable during rerun');
    release();await rerun;
    check(calls.slice(4).every(call=>call.assets.join(',')==='c,d'),'same reference resolves new images without rewiring');
    check(c.document.nodes[1].promptReferences[0].assetId===undefined,'dynamic reference remains unpinned');
    const saved=structuredClone(c.document);saved.run.status='running';saved.run.steps.source.status='running';saved.nodes[0].outputs={};
    sessionStorage.setItem('workflow-image-chain-recovery',JSON.stringify({revision:1,document:saved}));
    api.recentGenSessions=async()=>[{id:saved.run.steps.source.jobId,status:'done',turns:[{turn_key:'manual-later',images:['wrong.png']},{turn_key:saved.run.steps.source.turnKey,images:['c.png','d.png']}]}];
    const recovered=new CanvasWorkflowController('image-chain-recovery');await recovered.load();await recovered.continue();
    check(recovered.document.run.status==='done'&&recovered.document.nodes[0].outputs.image.assetIds.join(',')==='c,d'&&calls.length===6,'resume selects original turn and never resubmits');
    fail=true;delay=false;await c.start('source');
    check(c.document.run.status==='failed'&&calls.length===7&&!c.document.nodes[0].outputs.image,'failed rerun cannot feed stale images to downstream');
  });
  // Actual UI: wire before results; history replaces both current and old session cards.
  await page.evaluate(async()=>{
    const {canvasWorkflowController}=await import('/src/lib/canvasWorkflowRuntime.ts');
    const {newWorkflowNode}=await import('/src/lib/canvasWorkflow.ts');
    await canvasWorkflowController('p').edit([{...newWorkflowNode('generation',80,100,'codex'),id:'ui-source',prompt:'source'}, {...newWorkflowNode('generation',1100,100,'codex'),id:'ui-target'}]);
    const snapshot=window.snapshot();snapshot.nodes=snapshot.nodes.filter(n=>n.id==='old');snapshot.view={...snapshot.view,panX:50,panY:70,zoom:0.8};sessionStorage.setItem('reference-fixture',JSON.stringify(snapshot));
  });
  await page.reload();const source=page.locator('[data-workflow-card="ui-source"]'),target=page.locator('[data-workflow-card="ui-target"]');await source.waitFor();
  const history=source.getByRole('button',{name:'生成历史',exact:true});
  await history.click();await page.getByText('暂无生成会话',{exact:true}).waitFor();
  await page.keyboard.press('Escape');assert.equal(await history.getAttribute('aria-expanded'),'false');
  await source.getByRole('button',{name:'输出：图片',exact:true}).click();await target.getByRole('button',{name:'输入：图片',exact:true}).click();
  await target.getByRole('textbox',{name:'卡片指令',exact:true}).pressSequentially('@');
  const option=page.getByRole('option').filter({hasText:'生成结果 1'});await option.click();
  await page.evaluate(async()=>{
    const {canvasWorkflowController}=await import('/src/lib/canvasWorkflowRuntime.ts');const c=canvasWorkflowController('p');
    if(c.document.nodes[1].promptReferences?.length!==1||c.document.nodes[1].promptReferences[0].assetId)throw new Error('reference must follow output');
    const canvas=window.snapshot(),base=canvas.nodes[0];
    for(const [id,y] of [['session-old',100],['session-new',420]])canvas.nodes.push({...base,id,kind:'prompt',assetId:null,role:null,x:570,y,width:260,height:180,createdAt:1790121600+y,positionLocked:true,payloadJson:JSON.stringify({schema_version:1,job_id:id,turn_key:'one',text:id,status:'succeeded',provider:'codex'})});
    for(const [assetId,job,turn] of [['a','session-old','one'],['b','session-old','one'],['c','session-new','one'],['d','session-new','later']])canvas.nodes.push({...base,id:'result-'+assetId,assetId,hiddenAt:1,role:'output',payloadJson:JSON.stringify({execution:{job_id:job,turn_key:turn}})});
    sessionStorage.setItem('reference-fixture',JSON.stringify(canvas));
    await c.edit(c.document.nodes.map(n=>n.id==='ui-source'?{...n,sessionNodeIds:['session-old','session-new'],activeSessionNodeId:'session-old'}:n));
  });
  await page.reload();await source.waitFor();
  const wire=page.locator('[data-workflow-target="ui-target"]');await wire.waitFor();
  const directPath=await wire.getAttribute('d');
  assert.match(directPath,/^M 400 /,'wire starts at generator image socket');
  assert.equal(await page.locator('[data-canvas-node-id="session-old"],[data-canvas-node-id="session-new"]').count(),0);
  assert.equal(await page.locator('[data-workflow-session-output="session-old"],[data-workflow-session-link]').count(),0);
  await history.click();const popup=page.getByRole('dialog',{name:'生成历史',exact:true});await popup.waitFor();
  assert.deepEqual(await popup.locator('[data-workflow-history-session]').evaluateAll(rows=>rows.map(row=>row.dataset.workflowHistorySession)),['session-new','session-old']);
  assert.equal(await popup.locator('time').first().getAttribute('datetime'),new Date((1790121600+420)*1000).toISOString());
  const oldRow=popup.locator('[data-workflow-history-session="session-old"]'),newRow=popup.locator('[data-workflow-history-session="session-new"]');
  await newRow.getByRole('img',{name:'会话产物',exact:true}).waitFor();
  assert.equal(await oldRow.locator('[data-asset-id]').getAttribute('data-asset-id'),'a');
  assert.equal(await newRow.locator('[data-asset-id]').getAttribute('data-asset-id'),'c','cover must use this turn, not later output');
  assert.equal(await oldRow.locator('.workflow-history-image-count').textContent(),'2 张');
  assert.equal(await newRow.locator('.workflow-history-image-count').count(),0);
  await newRow.getByRole('img',{name:'会话产物',exact:true}).hover();
  await page.waitForFunction(()=>Array.from(document.body.children).some(el=>el.tagName==='IMG'&&el.style.zIndex==='100000'));
  const enlarged=page.locator('body > img[style*="z-index: 100000"]');
  assert.equal(await enlarged.getAttribute('src'),await newRow.locator('img').getAttribute('src'));
  assert.equal(await enlarged.evaluate(el=>getComputedStyle(el).pointerEvents),'none');
  const previewRect=await enlarged.boundingBox();assert.ok(previewRect.width>48&&previewRect.x>=0&&previewRect.x+previewRect.width<=1800);
  await mkdir('.tmp/workflow',{recursive:true});await page.screenshot({path:'.tmp/workflow/generation-history.png'});
  await oldRow.getByRole('img',{name:'会话产物',exact:true}).click();
  await enlarged.waitFor({state:'detached'});
  await page.locator('[data-project-inspector="generation"]').waitFor();
  assert.match(await page.locator('[data-project-inspector="generation"]').innerText(),/session-old/,'saved session opens even when job is outside in-memory history');
  await page.keyboard.press('Escape');
  await page.evaluate(async()=>{const {canvasWorkflowController}=await import('/src/lib/canvasWorkflowRuntime.ts');const c=canvasWorkflowController('p');await c.edit(c.document.nodes.map(n=>n.id==='ui-source'?{...n,activeSessionNodeId:'session-new'}:n));});
  assert.equal(await wire.getAttribute('d'),directPath,'new session does not move the wire');
  assert.equal(await page.locator('[data-canvas-node-id="session-old"]').count(),0);
  await page.reload();await source.waitFor();await history.click();await popup.waitFor();
  assert.equal(await popup.locator('[data-workflow-history-session]').count(),2);
  await page.mouse.click(1500,900);await popup.waitFor({state:'detached'});
  // Many sessions stay in a bounded scrollable bubble; scrolling must not zoom the board.
  await page.evaluate(async()=>{
    const {canvasWorkflowController}=await import('/src/lib/canvasWorkflowRuntime.ts');const c=canvasWorkflowController('p');
    const canvas=window.snapshot(),base=canvas.nodes.find(n=>n.id==='session-new');const ids=[];
    for(let i=0;i<24;i++){const id='history-'+i;ids.push(id);canvas.nodes.push({...base,id,createdAt:base.createdAt+i+1,payloadJson:JSON.stringify({schema_version:1,job_id:id,turn_key:'one',text:'历史会话 '+i,status:'done',provider:'codex'})});
      canvas.nodes.push({...base,id:'output-'+id,kind:'asset',assetId:'a',hiddenAt:1,role:'output',payloadJson:JSON.stringify({execution:{job_id:id,turn_key:'one'}})});}
    sessionStorage.setItem('reference-fixture',JSON.stringify(canvas));await c.edit(c.document.nodes.map(n=>n.id==='ui-source'?{...n,sessionNodeIds:[...n.sessionNodeIds,...ids]}:n));
  });
  await page.reload();await source.waitFor();await history.click();await popup.waitFor();
  assert.equal(await popup.locator('[data-workflow-history-session]').count(),26);
  const plane=page.locator('.canvas-plane'),before=await plane.getAttribute('style');
  await popup.locator('[data-workflow-history-session]').first().getByRole('img',{name:'会话产物',exact:true}).hover();
  await enlarged.waitFor();await page.mouse.wheel(0,500);
  await page.waitForFunction(()=>document.querySelector('.workflow-generation-history-popover').scrollTop>0);
  await enlarged.waitFor({state:'detached'});
  assert.equal(await plane.getAttribute('style'),before);
  await page.keyboard.press('Escape');assert.equal(await history.evaluate(el=>el===document.activeElement),true);
  await page.getByRole('button',{name:'适应内容',exact:true}).click();
  await mkdir('.tmp/workflow',{recursive:true});await page.screenshot({path:'.tmp/workflow/generation-session-chain.png'});
  assert.deepEqual(errors,[]);
  console.log('generation image chain: waiting, fanout, rerun, failure, exact-turn recovery, dynamic @ input, direct wiring, history panel, dismissal and reload passed');
} finally {await browser.close();await server.close();}
