import assert from 'node:assert/strict';
import { mkdir } from 'node:fs/promises';
import { createServer } from 'vite';
import { chromium } from '../../html-renderer/node_modules/playwright/index.mjs';
const production = process.env.BOWERBIRD_WORKFLOW_PRODUCTION === '1';
const server = await createServer({ cacheDir: production ? '.tmp/workflow-agent-production-'+'canvas-workflow-agent-images.test.mjs' : undefined, define: production ? { 'import.meta.env.DEV': 'false', 'import.meta.env.PROD': 'true' } : undefined, configFile: false, root: process.cwd(), server: { host: '127.0.0.1', port: 1628, strictPort: true, hmr: false, watch: null } });
await server.listen();
const browser = await chromium.launch({ channel: 'chrome', headless: true });
const page = await browser.newPage({ viewport: { width: 1600, height: 1200 } });
try {
  await page.goto('http://127.0.0.1:1628/scripts/fixtures/canvas-reference/preview.html');
  await page.locator('[data-canvas-node-id="old"]').waitFor();
  await page.evaluate(() => { const snapshot = window.snapshot(); snapshot.nodes = snapshot.nodes.filter(node => node.id !== 'far'); sessionStorage.setItem('reference-fixture', JSON.stringify(snapshot)); });
  await page.reload(); await page.locator('[data-canvas-node-id="old"]').waitFor();
  const result = await page.evaluate(async () => {
    const { api } = await import('/src/lib/api.ts');
    const { canvasWorkflowController, CanvasWorkflowController } = await import('/src/lib/canvasWorkflowRuntime.ts');
    const { newWorkflowNode, workflowOutputs } = await import('/src/lib/canvasWorkflow.ts');
    const { useStore } = await import('/src/store.ts');
    const check = (ok, message) => { if (!ok) throw Error(message); };
    useStore.setState({ cloudAuth: null, cloudEntitlement: null });
    let answer = { images: ['b.png', 'a.png'] }, submissions = 0, imports = 0, delivered = true, ready = true, broken = false;
    api.agentDsWorkflowStart = async () => { submissions++; return { autoDelivered: delivered, path: 'isolated' }; };
    api.agentDsWorkflowResult = async requestId => ready ? { schemaVersion: 1, requestId, ...answer } : null;
    api.agentDsWorkflowIngestImages = async () => {
      imports++;
      if (broken) throw Error('图片无法解码');
      const assets = await api.getAssetsByIds(['b', 'a']);
      return ['b', 'a'].map(id => assets.find(asset => asset.id === id));
    };
    let c = canvasWorkflowController('p'); await c.load();
    const agent = { ...newWorkflowNode('agent', 40, 600, ''), id: 'image-agent', prompt: '返回两张图片，并附上说明' };
    check(workflowOutputs(agent).some(port => port.id === 'image'), 'image port available before execution');
    check(!workflowOutputs({ ...agent, agentTransport: 'cloud' }).some(port => port.id === 'image'), 'Cloud advertises text only');
    await c.edit([agent]);
    answer = { text: JSON.stringify({ format: 'bowerbird-table', columns: ['项目'], rows: [['旧内容']] }) };
    await c.start(agent.id, true);
    const oldTable = c.document.nodes[0].resultNodeIds[0];
    answer = { images: ['b.png', 'a.png'] };
    await c.start(agent.id, true);
    check(JSON.parse(window.snapshot().nodes.find(n => n.id === oldTable).payloadJson).cells.flat().every(cell => !cell.text), 'image-only rerun clears previous automatic table content');
    check(c.document.run.status === 'done' && !c.document.nodes[0].outputs.text, JSON.stringify(c.issue));
    check(c.document.nodes[0].outputs.image.assetIds.join() === 'b,a', 'image-only result preserves order');
    const base = window.snapshot().nodes[0];
    for (const id of ['image-target', 'text-target']) await api.projectCanvasNodeCreate({ ...base, id, x: 500, y: id === 'image-target' ? 650 : 950, kind: 'note', role: null, assetId: null,
      payloadJson: JSON.stringify({ schema_version: 1, note_type: 'text', title: id, text: '', member_ids: [], cells: [[{ id: 'first', text: '' }, { id: 'keep', text: '邻格保留' }]] }) });
    const imageWriter = { ...newWorkflowNode('text', 0, 0, ''), id: 'image-writer', textTarget: { nodeId: 'image-target', cellId: 'first', image: true }, inputs: { image: [{ nodeId: agent.id, portId: 'image' }] } };
    const textWriter = { ...newWorkflowNode('text', 0, 0, ''), id: 'text-writer', textTarget: { nodeId: 'text-target', cellId: 'first' }, inputs: { text: [{ nodeId: agent.id, portId: 'text' }] } };
    answer = { images: ['b.png', 'a.png'], text: '两张图片的说明' };
    await c.edit([agent, imageWriter, textWriter]); await c.start(agent.id, true);
    check(c.document.run.status === 'done', JSON.stringify(c.issue));
    const cells = id => JSON.parse(window.snapshot().nodes.find(n => n.id === id).payloadJson).cells;
    check(cells('image-target')[0][0].image_refs.map(ref => ref.asset_id).join() === 'b,a', 'image output reaches cell in order');
    check(cells('text-target')[0][0].text === answer.text && cells('image-target')[0][1].text === '邻格保留', 'mixed delivery preserves neighbors');
    delivered = false; ready = false; await c.start(agent.id, true);
    const before = submissions;
    check(c.document.run.status === 'waiting', 'undelivered result waits');
    const recovered = new CanvasWorkflowController('p'); await recovered.load();
    ready = true; await recovered.continue();
    check(submissions === before && recovered.document.run.status === 'done', 'reload recovers without resubmission');
    c = recovered; delivered = true;
    broken = true; await c.start(agent.id, true);
    check(c.document.run.status === 'failed' && !c.document.nodes[0].outputs.image, 'failed import does not publish output');
    broken = false; answer = {};
    const priorImports = imports; await c.start(agent.id, true);
    check(c.document.run.status === 'failed' && imports === priorImports, 'empty result fails before import');
    answer = { images: ['b.png', 'a.png'] };
    const ingest = api.agentDsWorkflowIngestImages;
    let release, started;
    const entered = new Promise(resolve => { started = resolve; });
    api.agentDsWorkflowIngestImages = async () => { started(); await new Promise(resolve => { release = resolve; }); return ingest(); };
    const running = c.start(agent.id, true); await entered;
    const stopping = c.stop(); release(); await Promise.all([running, stopping]);
    check(c.document.run.status === 'stopped' && !c.document.nodes[0].outputs.image, 'stop discards late result');
    api.agentDsWorkflowIngestImages = ingest;
    answer = { images: ['b.png', 'a.png'], text: '两张图片的说明' };
    await c.start(agent.id, true); check(c.document.run.status === 'done', JSON.stringify(c.issue));
    window.save(); return { submissions, imports };
  });
  await page.reload();
  await page.getByRole('button', { name: '适应内容', exact: true }).click();
  const preview = page.locator('.workflow-image-result'); await preview.waitFor();
  assert.equal(await preview.getByRole('img').count(), 2);
  await preview.getByRole('button', { name: '查看返回图片 1' }).click();
  await page.locator('.workflow-image-preview').waitFor();
  assert.ok(await page.locator('.workflow-image-preview').evaluate(img => img.complete && img.naturalWidth > 0));
  await page.keyboard.press('Escape');
  await mkdir('.tmp/workflow', { recursive: true });
  await page.screenshot({ path: '.tmp/workflow/agent-images.png' });
  console.log('PASS Agent image-only/mixed results, content delivery, reload recovery, failure, cancellation and preview', result);
} finally { await browser.close(); await server.close(); }
