import assert from 'node:assert/strict';
import { createServer } from 'vite';
import { chromium } from '../../html-renderer/node_modules/playwright/index.mjs';
const server = await createServer({ configFile: false, root: process.cwd(), server: { host: '127.0.0.1', port: 1587, strictPort: true, hmr: false, watch: null } });
await server.listen();
const browser = await chromium.launch({ channel: 'chrome', headless: true });
const page = await browser.newPage({ viewport: { width: 1500, height: 1000 } });
try {
  await page.goto('http://127.0.0.1:1587/scripts/fixtures/canvas-reference/preview.html');
  await page.locator('[data-canvas-node-id="old"]').waitFor();
  await page.evaluate(() => { const canvas = window.snapshot(); canvas.nodes = canvas.nodes.filter(n => n.id !== 'far'); sessionStorage.setItem('reference-fixture', JSON.stringify(canvas)); });
  await page.reload(); await page.locator('[data-canvas-node-id="old"]').waitFor();
  await page.evaluate(async () => {
    const { api } = await import('/src/lib/api.ts');
    const { canvasWorkflowController } = await import('/src/lib/canvasWorkflowRuntime.ts');
    const { newWorkflowNode } = await import('/src/lib/canvasWorkflow.ts');
    const { useStore } = await import('/src/store.ts');
    const check = (value, message) => { if (!value) throw new Error(message); };
    const base = window.snapshot().nodes[0];
    const cell = (id, text) => ({ id, text, bold: false, italic: false, align: 'left' });
    for (const [id, x] of [['source', 20], ['target', 470]]) await api.projectCanvasNodeCreate({ ...base, id, kind: 'note', role: null, assetId: null, x, y: 60, width: 380, height: 280,
      payloadJson: JSON.stringify({ schema_version: 1, note_type: 'text', text: '', cells: [[cell('a', '  原文\n第二行\t末尾  '), cell('b', '保留内容')]], member_ids: [] }) });
    const c = canvasWorkflowController('p'); await c.load();
    const read = () => JSON.parse(window.snapshot().nodes.find(n => n.id === 'target').payloadJson);
    await c.bindTextInput('target', undefined, { canvasNodeId: 'source', cellId: 'a' }, 'text');
    let note = read();
    check(note.cells.length === 2 && note.cells[1][0].text === '  原文\n第二行\t末尾  ', 'whole input appends first column with exact text');
    check(note.cells[1][1].text === '' && note.cells[0][1].text === '保留内容', 'other cells stay intact');
    const append = c.document.nodes.find(n => n.textTarget?.append);
    await c.start(append.id, true);
    check(read().cells.length === 2, 'rerun updates the same row');
    await c.bindTextInput('target', 'b', { assetId: 'existing' }, 'image');
    note = read();
    check(note.cells[0][1].text === '@图片1' && note.cells[0][1].image_refs[0].asset_id === 'existing', 'image input stores real reference identity');
    const imageWriter = c.document.nodes.find(n => n.textTarget?.cellId === 'b');
    const generate = { ...newWorkflowNode('generation', 950, 60, 'codex'), id: 'generate', inputs: { image: [{ canvasNodeId: 'target', cellId: 'b' }] } };
    generate.prompt = '@[cell]';
    generate.promptReferences = [{ id: 'cell', type: 'image', input: generate.inputs.image[0], label: '图片单元格' }];
    await c.edit([...c.document.nodes, generate]);
    let submitted = 0;
    useStore.setState({ startGeneration: async (prompt, assets, ...args) => { submitted++; check(prompt === '@图片1' && assets[0].id === 'existing', 'text output forwards image to generation'); api.localAgentFindAssetId = async () => "existing"; useStore.setState(s => ({ genJobs: { ...s.genJobs, [args[10].jobId]: { turns: [{ turnKey: args[10].turnKey, images: ["out.png"] }] } } })); return { accepted: true, jobId: args[10].jobId }; } });
    await c.start(imageWriter.id);
    check(c.document.run.status === 'done' && submitted === 1 && c.document.run.order.join(',') === `${imageWriter.id},generate`, 'writer advances downstream');
    await c.edit(c.document.nodes.map(n => n.id === 'generate' ? { ...n, prompt: '@[image] @[cell]', promptReferences: [...n.promptReferences, { id: 'image', type: 'image', input: { assetId: 'a' }, assetId: 'a', label: '图片 1' }], inputs: { ...n.inputs, image: [{ assetId: 'a' }, ...n.inputs.image] } } : n));
    useStore.setState({ startGeneration: async (prompt, assets, ...args) => { check(prompt === '@图片1 @图片2' && assets.map(a => a.id).join(',') === 'a,existing', 'index maps to the combined reference order'); api.localAgentFindAssetId = async () => "existing"; useStore.setState(s => ({ genJobs: { ...s.genJobs, [args[10].jobId]: { turns: [{ turnKey: args[10].turnKey, images: ["out.png"] }] } } })); return { accepted: true, jobId: args[10].jobId }; } });
    await c.start('generate');
    check(c.document.run.status === 'done', 'mixed references complete');
    let cycle = false;
    try { await c.bindTextInput('target', 'b', { canvasNodeId: 'target', cellId: 'b' }, 'text'); } catch { cycle = true; }
    check(cycle && read().cells[0][1].text === '@图片1', 'self-loop rejected before changing content');
    const upstream = { ...newWorkflowNode('instruction', 0, 450, 'codex'), id: 'upstream', action: 'reuse', inputs: { image: [{ assetId: 'a' }] } };
    await c.edit([...c.document.nodes, upstream]);
    await c.bindTextInput('target', 'a', { nodeId: upstream.id, portId: 'text' }, 'text');
    check(read().cells[0][0].text === '  原文\n第二行\t末尾  ', 'empty upstream waits without destroying text');
    await c.start(upstream.id);
    check(read().cells[0][0].text === '保持产品主体，生成清晨场景', 'upstream execution writes cell');
    window.save();
  });
  await page.reload();
  const target = page.locator('[data-canvas-node-id="target"]'); await target.waitFor();
  await page.getByRole('button', { name: '适应内容', exact: true }).click();
  const imageCell = target.getByRole('cell').nth(1);
  assert.equal(await imageCell.locator('.canvas-image-preview img').count(), 1);
  await page.screenshot({ path: '.tmp/workflow/text-image-index.png' });
  await imageCell.hover();
  const input = target.getByRole('button', { name: '输入第 1 行第 2 列', exact: true });
  await input.click({ button: 'right' });
  await page.waitForFunction(() => !JSON.parse(sessionStorage.getItem('workflow-p')).document.nodes.some(n => n.textTarget?.cellId === 'b'));
  assert.equal(await imageCell.locator('.canvas-image-preview img').count(), 1);
  const source = page.locator('[data-canvas-node-id="source"]');
  await source.getByRole('cell').first().hover();
  await source.getByRole('button', { name: '输出第 1 行第 1 列文本', exact: true }).click();
  await target.getByRole('cell').nth(1).hover(); await input.click();
  await page.waitForFunction(() => JSON.parse(window.snapshot().nodes.find(n => n.id === 'target').payloadJson).cells[0][1].text === '  原文\n第二行\t末尾  ');
  await imageCell.locator('.canvas-image-preview').waitFor({ state: 'detached' });
  await source.getByRole('cell').first().hover();
  await source.getByRole('button', { name: '输出第 1 行第 1 列文本', exact: true }).click();
  await target.hover(); await target.getByRole('button', { name: '内容卡片输入', exact: true }).click();
  await page.waitForFunction(() => JSON.parse(window.snapshot().nodes.find(n => n.id === 'target').payloadJson).cells.length === 3);
  await page.waitForFunction(() => document.querySelectorAll('[data-canvas-node-id="target"] [role="row"]').length === 3);
  await page.screenshot({ path: '.tmp/workflow/text-inputs.png' });
  await page.getByRole('button', { name: '发条触发器', exact: true }).click();
  await target.getByLabel('第 1 行第 1 列', { exact: true }).click();
  const key = page.locator('[data-workflow-text-key="target"] .workflow-key');
  await key.waitFor();
  await page.evaluate(() => window.save()); await page.reload(); await key.waitFor();
  await page.evaluate(async () => {
    const { canvasWorkflowController } = await import('/src/lib/canvasWorkflowRuntime.ts');
    const { useStore } = await import('/src/store.ts');
    const { api } = await import('/src/lib/api.ts');
    const c = canvasWorkflowController('p'); await c.load();
    await c.edit(c.document.nodes.map(n => n.id === 'generate' ? { ...n, inputs: { image: [{ assetId: 'a' }], text: [{ canvasNodeId: 'target', cellId: 'b' }] }, promptReferences: n.promptReferences.map(ref => ref.id === 'cell' ? { ...ref, type: 'text' } : ref) } : n));
    // The target still has upstream writers; the key must forward the current edited cell.
    const table = window.snapshot().nodes.find(n => n.id === 'target');
    const note = JSON.parse(table.payloadJson);
    note.cells[0][1].text = '当前内容 @图片1';
    note.cells[0][1].image_refs = [{ asset_id: 'existing', token: '@图片1' }];
    await api.projectCanvasNoteUpdate(table.id, JSON.stringify(note));
    api.generationHistory = async () => { throw new Error('must not run upstream'); };
    window.textKeyCalls = 0;
    useStore.setState({ startGeneration: async (prompt, assets, ...args) => {
      if (prompt !== '@图片1 当前内容 @图片2' || assets.map(a => a.id).join(',') !== 'a,existing') throw new Error('wrong current content or references');
      window.textKeyCalls++; await new Promise(resolve => { window.releaseTextKey = resolve; }); api.localAgentFindAssetId = async () => "existing"; useStore.setState(s => ({ genJobs: { ...s.genJobs, [args[10].jobId]: { turns: [{ turnKey: args[10].turnKey, images: ["out.png"] }] } } })); return { accepted: true };
    } });
  });
  await key.click();
  await page.waitForFunction(() => window.textKeyCalls === 1 || JSON.parse(sessionStorage.getItem('workflow-p')).document.run?.status === 'failed');
  assert.equal(await page.evaluate(() => window.textKeyCalls), 1, await page.evaluate(() => JSON.stringify(JSON.parse(sessionStorage.getItem('workflow-p')).document.run)));
  await key.hover(); await page.getByRole('tooltip').waitFor();
  assert.match(await page.getByRole('tooltip').innerText(), /生成卡片/);
  await page.evaluate(() => window.releaseTextKey());
  await page.waitForFunction(() => JSON.parse(sessionStorage.getItem('workflow-p')).document.run.status === 'done');
  const run = await page.evaluate(() => JSON.parse(sessionStorage.getItem('workflow-p')).document.run);
  assert.equal(run.order.length, 2); assert.equal(run.order[1], 'generate');
  await key.click({ button: 'right' }); await key.waitFor({ state: 'detached' });
  console.log('text key: native attachment, persistence, current edited content, image forwarding, no upstream rerun, progress and detach passed');
  console.log('text inputs: append, exact replacement, image identity, downstream execution, cycles, reload, click wiring, disconnect passed');
} finally { await browser.close(); await server.close(); }
