import assert from "node:assert/strict";
import { createServer } from "vite";
import { chromium } from "../../html-renderer/node_modules/playwright/index.mjs";
const server = await createServer({ server: { host: "127.0.0.1", port: 1578, strictPort: true, hmr: false, watch: null } });
await server.listen();
const browser = await chromium.launch({ channel: "chrome", headless: true });
const page = await browser.newPage({ viewport: { width: 1800, height: 1200 } });
const errors = [];
page.on("pageerror", error => errors.push(error.message));
const node = id => page.locator(`[data-canvas-node-id="${id}"]`);
const source = id => page.locator(`.canvas-source-panel [data-asset-id="${id}"]`);
const hide = () => page.getByRole("menuitem", { name: "从库中删除 · 在画布保留", exact: true });
try {
  await page.goto("http://127.0.0.1:1578/scripts/fixtures/canvas-reference/preview.html?source-library&canvas-library");
  await node("old").waitFor();
  // Only project-library images have the entry; it requires a retained visible canvas instance.
  await source("a").click({ button: "right" });
  await hide().waitFor();
  assert.equal(await hide().isDisabled(), true);
  await page.keyboard.press("Escape");
  await page.getByRole("tab", { name: "中央素材", exact: true }).click();
  await source("existing").click({ button: "right" });
  assert.equal(await hide().count(), 0);
  await page.keyboard.press("Escape");
  await page.getByRole("tab", { name: "项目素材", exact: true }).click();
  const before = await page.evaluate(() => window.snapshot());
  const geometry = await node("old").boundingBox();
  const original = await node("old").locator(":scope > img").getAttribute("src");
  await page.evaluate(() => { window.failLibraryVisibility = true; });
  await source("existing").click({ button: "right" });
  await hide().click();
  await page.getByText(/模拟归属修改失败/).waitFor();
  assert.equal(await source("existing").count(), 1);
  assert.deepEqual(await page.evaluate(() => window.snapshot()), before);
  await page.evaluate(() => { window.failLibraryVisibility = false; });
  await hide().click();
  await source("existing").waitFor({ state: "detached" });
  assert.deepEqual(await node("old").boundingBox(), geometry);
  assert.equal(await node("old").locator(":scope > img").getAttribute("src"), original);
  assert.deepEqual(await page.evaluate(() => window.snapshot()), before);
  await page.getByRole("tab", { name: "中央素材", exact: true }).click();
  await page.waitForFunction(() => !document.querySelector('.canvas-source-panel [data-asset-id="existing"]'));
  await page.evaluate(() => window.save());
  await page.reload();
  await node("old").waitFor();
  assert.equal(await source("existing").count(), 0);
  await node("old").click({ button: "right", position: { x: 30, y: 30 } });
  await page.getByRole("menuitem", { name: "加入素材库", exact: true }).click();
  await source("existing").waitFor();
  assert.deepEqual(await page.evaluate(() => window.snapshot()), before);
  assert.deepEqual(await page.evaluate(() => window.calls.filter(call => call.command === "delete_asset_with_mode")), [], "visibility never invokes deletion");
  assert.deepEqual(errors, []);
  console.log("PASS project-only menu entry, unplaced guard, failure retention, hide/restore, canvas geometry/original and reload.");
} finally { await browser.close(); await server.close(); }
