import assert from 'node:assert/strict';
import { createServer } from 'vite';
import { chromium } from '../../html-renderer/node_modules/playwright/index.mjs';
const server = await createServer({ configFile: false, root: process.cwd(), server: { host: '127.0.0.1', port: 1588, strictPort: true, hmr: false, watch: null } });
await server.listen();
const browser = await chromium.launch({ channel: 'chrome', headless: true });
const page = await browser.newPage({ viewport: { width: 1800, height: 1200 } });
try {
  await page.goto('http://127.0.0.1:1588/scripts/fixtures/canvas-reference/preview.html');
  await page.locator('[data-canvas-node-id="old"]').waitFor();
  await page.evaluate(() => { const s = window.snapshot(); s.nodes = s.nodes.filter(n => n.id !== 'far'); sessionStorage.setItem('reference-fixture', JSON.stringify(s)); });
  await page.reload();
  assert.equal(await page.getByRole('button', { name: '新增触发器卡片', exact: true }).count(), 0);
  const tool = await page.getByRole('button', { name: '发条触发器', exact: true }).boundingBox();
  await page.mouse.move(tool.x + tool.width / 2, tool.y + tool.height / 2); await page.mouse.down();
  await page.mouse.move(1400, 300, { steps: 12 }); await page.mouse.up();
  const trigger = page.locator('.workflow-card.is-trigger'); await trigger.waitFor();
  assert.equal(await trigger.locator('textarea,.workflow-port.is-input').count(), 0);
  await page.getByRole('button', { name: '新增指令卡片', exact: true }).click();
  const instruction = page.locator('.workflow-card.is-instruction'); await instruction.getByLabel('指令功能').selectOption('reuse');
  await page.evaluate(async () => {
    const { canvasWorkflowController } = await import('/src/lib/canvasWorkflowRuntime.ts');
    const c = canvasWorkflowController('p');
    await c.edit(c.document.nodes.map(n => n.kind === 'instruction' ? { ...n, inputs: { image: [{ assetId: 'existing' }] } } : n));
  });
  await page.getByRole('button', { name: '适应内容', exact: true }).click();
  await trigger.getByRole('button', { name: '输出：触发', exact: true }).click();
  await instruction.locator('header strong').click();
  await page.waitForFunction(() => JSON.parse(sessionStorage.getItem('workflow-p')).document.nodes.find(n => n.kind === 'instruction').inputs.signal?.length === 1);
  assert.equal(await instruction.locator('[data-workflow-input="signal"]').count(), 0);
  const outputBox = await trigger.getByRole('button', { name: '输出：触发', exact: true }).boundingBox();
  const targetBox = await instruction.locator('header strong').boundingBox();
  await page.mouse.move(outputBox.x + 5, outputBox.y + 5); await page.mouse.down();
  await page.mouse.move(targetBox.x + 15, targetBox.y + 10, { steps: 12 }); await page.mouse.up();
  await trigger.getByRole('button', { name: '触发下游', exact: true }).click();
  await page.waitForFunction(() => JSON.parse(sessionStorage.getItem('workflow-p')).document.run?.status === 'done');
  const doc = await page.evaluate(() => JSON.parse(sessionStorage.getItem('workflow-p')).document);
  assert.equal(doc.run.order.length, 2); assert.equal(doc.nodes.find(n => n.kind === 'instruction').inputs.signal.length, 1);
  assert.match(doc.nodes.find(n => n.kind === 'instruction').outputs.text.text, /保持产品主体/);
  await page.screenshot({ path: '.tmp/workflow/trigger-card.png' });
  await page.evaluate(() => window.save()); await page.reload(); await trigger.waitFor();
  assert.equal(await page.locator('[data-workflow-signal-link]').count(), 1);
  await instruction.getByRole('button', { name: '断开触发器连接', exact: true }).click({ button: 'right' });
  await page.waitForFunction(() => !document.querySelector('[data-workflow-signal-link]'));
  const keyTool = await page.getByRole('button', { name: '发条触发器', exact: true }).boundingBox();
  const cardHeader = await instruction.locator('header strong').boundingBox();
  await page.mouse.move(keyTool.x + 10, keyTool.y + 10); await page.mouse.down();
  await page.mouse.move(cardHeader.x + 10, cardHeader.y + 10, { steps: 12 }); await page.mouse.up();
  await instruction.getByRole('button', { name: '上发条，运行工作流', exact: true }).waitFor();
  await trigger.getByRole('button', { name: '输出：触发', exact: true }).click(); await instruction.locator('header strong').click();
  await instruction.getByRole('button', { name: '断开触发器连接', exact: true }).waitFor();
  assert.equal(await instruction.getByRole('button', { name: '上发条，运行工作流', exact: true }).count(), 0);
  await instruction.getByRole('button', { name: '断开触发器连接', exact: true }).click({ button: 'right' });
  await page.evaluate(async () => {
    const { api } = await import('/src/lib/api.ts');
    const { CanvasWorkflowController } = await import('/src/lib/canvasWorkflowRuntime.ts');
    const { newWorkflowNode, workflowOrder } = await import('/src/lib/canvasWorkflow.ts');
    const { useStore } = await import('/src/store.ts');
    const make = (id, kind) => ({ ...newWorkflowNode(kind, 0, 0, 'codex'), id });
    const sw = make('switch', 'trigger'), other = make('other', 'trigger');
    const a = { ...make('a', 'instruction'), action: 'reuse', inputs: { image: [{ assetId: 'existing' }], signal: [{ nodeId: 'switch', portId: 'signal' }, { nodeId: 'other', portId: 'signal' }] } };
    const b = { ...a, id: 'b', inputs: { ...a.inputs, text: [{ nodeId: 'a', portId: 'text' }] } };
    const c = new CanvasWorkflowController('trigger-runtime'); await c.load(); await c.edit([sw, other, b, a]);
    await c.start('switch');
    if (c.document.run.status !== 'done' || c.document.run.order.join(',') !== 'switch,a,b' || c.document.run.lockedNodeIds.includes('other')) throw new Error('fanout must respect data dependencies and isolate other switches');
    const original = api.generationHistory; api.generationHistory = async () => { throw new Error('synthetic failure'); };
    await c.start('switch'); if (c.document.run.status !== 'failed' || c.document.run.steps.b.status !== 'pending') throw new Error('error must stop downstream'); api.generationHistory = original;
    if (workflowOrder(c.document.nodes, 'a').includes('switch')) throw new Error('independent run must not execute the switch');
    const base = window.snapshot().nodes[0];
    await api.projectCanvasNodeCreate({ ...base, id: 'switch-text', kind: 'note', role: null, assetId: null, payloadJson: JSON.stringify({ schema_version: 1, note_type: 'text', text: '当前文本', cells: [[{ id: 'cell', text: '当前文本', bold: false, italic: false, align: 'left' }]], member_ids: [] }) });
    const text = { ...make('text', 'text'), textSource: 'switch-text', inputs: { signal: [{ nodeId: 'switch', portId: 'signal' }] } };
    const gen = { ...make('gen', 'generation'), inputs: { text: [{ canvasNodeId: 'switch-text', cellId: 'cell' }] } };
    gen.prompt = '@[cell]';
    gen.promptReferences = [{ id: 'cell', type: 'text', input: gen.inputs.text[0], label: '文本 1' }];
    api.localAgentFindAssetId = async () => 'existing';
    useStore.setState({ startGeneration: async (...args) => {
      if (args[0] !== '当前文本') throw new Error('current text must pass through');
      const identity = args[12];
      useStore.setState(s => ({ genJobs: { ...s.genJobs, [identity.jobId]: { turns: [{ turnKey: identity.turnKey, images: ['result.png'] }] } } }));
      return { accepted: true };
    } });
    await c.edit([sw, text, gen]); await c.start('switch');
    if (c.document.run.status !== 'done' || c.document.run.order.join(',') !== 'switch,text,gen') throw new Error('switch must relay native text card');
  });
  console.log('trigger: creation, direct card attachment, dedup, execution, persistence, disconnect, fanout ordering, failure, independent runs and native text relay passed');
} finally { await browser.close(); await server.close(); }
