import assert from 'node:assert/strict';
import { createServer } from 'vite';
import { chromium } from '../../html-renderer/node_modules/playwright/index.mjs';
const server = await createServer({ configFile: false, root: process.cwd(), server: { host: '127.0.0.1', port: 1613, strictPort: true, hmr: false, watch: null } });
await server.listen();
const browser = await chromium.launch({ channel: 'chrome', headless: true });
const page = await browser.newPage({ viewport: { width: 1440, height: 1000 } });
const errors = []; page.on('pageerror', error => errors.push(error.message));
try {
  await page.goto('http://127.0.0.1:1613/scripts/fixtures/canvas-reference/preview.html');
  await page.locator('[data-canvas-node-id="old"]').waitFor();
  await page.getByRole('button', { name: '新增循环卡片', exact: true }).click();
  const card = page.locator('.workflow-card.is-loop'); await card.waitFor();
  await card.getByRole('combobox', { name: '循环方式' }).selectOption('rows');
  await page.waitForFunction(() => JSON.parse(sessionStorage.getItem('workflow-p')).document.nodes.some(node => node.kind === 'loop' && node.loopMode === 'rows'));
  await page.reload(); await card.waitFor();
  assert.equal(await card.getByRole('combobox', { name: '循环方式' }).inputValue(), 'rows');
  assert.equal(await card.locator('textarea').count(), 0);
  await page.evaluate(async () => { const { canvasWorkflowController } = await import('/src/lib/canvasWorkflowRuntime.ts'); const c = canvasWorkflowController('p'); await c.edit(c.document.nodes.map(node => ({ ...node, x: node.x - 180, y: node.y - 600 }))); });
  await page.screenshot({ path: '.tmp/workflow/loop-card.png' });
  console.log(await page.evaluate(async () => {
    const { api } = await import('/src/lib/api.ts');
    const { useStore } = await import('/src/store.ts');
    const { CanvasWorkflowController } = await import('/src/lib/canvasWorkflowRuntime.ts');
    const { newWorkflowNode } = await import('/src/lib/canvasWorkflow.ts');
    const { workflowLoopRows } = await import('/src/lib/workflowLoop.ts');
    const { cloneCanvasClipboard } = await import('/src/lib/canvasClipboard.ts');
    const check = (value, message) => { if (!value) throw Error(message); };
    const until = async (fn, message) => { for (let i = 0; i < 400; i++) { if (fn()) return; await new Promise(resolve => setTimeout(resolve, 10)); } throw Error(message); };
    const loop = () => ({ ...newWorkflowNode('loop', 0, 0, 'codex'), id: 'loop', inputs: { image: [{ assetId: 'a' }, { assetId: 'b' }] } });
    const gen = (id, producer = 'loop') => {
      const input = { nodeId: producer, portId: 'image' };
      return { ...newWorkflowNode('generation', 420, 0, 'codex'), id, prompt: `${id} @[image]`, inputs: { image: [input] }, promptReferences: [{ id: 'image', type: 'image', input, label: '当前项' }] };
    };
    let c, submissions = [], cancelled = [];
    api.localAgentFindAssetId = async path => path.replace('.png', '');
    api.cancelCodexCreate = async id => { cancelled.push(id); };
    useStore.setState({ startGeneration: async (...args) => {
      const identity = args[12], persisted = JSON.parse(sessionStorage.getItem(`workflow-${c.projectId}`)).document.run;
      const name = args[0].split(' ')[0];
      check(persisted.steps[name].jobId === identity.jobId, 'identity saved before generation');
      check(persisted.loop.items.length === 2, 'input snapshot persisted before generation');
      check(persisted.loop.completed.length === persisted.loop.index, 'previous item durable before submit');
      const submission = { name, asset: args[1][0].id, identity }; submissions.push(submission);
      await new Promise(resolve => { submission.release = resolve; });
      useStore.setState(state => ({ genJobs: { ...state.genJobs, [identity.jobId]: { turns: [{ turnKey: identity.turnKey, images: [submission.asset + '.png'] }] } } }));
      return { accepted: true };
    } });
    const create = async (name, nodes) => { submissions = []; cancelled = []; c = new CanvasWorkflowController(name); await c.load(); await c.edit(nodes); return c; };
    await create('loop-order', [loop(), gen('A'), gen('B'), gen('child', 'A')]);
    let running = c.start('loop', true);
    await until(() => submissions.length === 2, 'first item forks start');
    check(submissions.every(job => job.asset === 'a'), 'only first item starts');
    submissions.find(job => job.name === 'A').release();
    await until(() => submissions.length === 3, 'child proceeds independently');
    check(submissions[2].name === 'child' && submissions[2].asset === 'a', 'child uses current item'); submissions[2].release();
    await new Promise(resolve => setTimeout(resolve, 40));
    check(submissions.length === 3 && c.document.run.loop.index === 0, 'next item waits for all branches'); submissions.find(job => job.name === 'B').release();
    await until(() => submissions.length === 5, 'second item forks start');
    check(submissions.slice(3).every(job => job.asset === 'b'), 'second item uses next input'); submissions[3].release(); submissions[4].release();
    await until(() => submissions.length === 6, 'second child starts'); submissions[5].release(); await running;
    check(c.document.run.status === 'done' && c.document.run.loop.completed.length === 2, 'both completed');
    check(new Set(submissions.map(job => job.identity.jobId)).size === 6, 'fresh identity for each step/item');
    check(c.document.run.loop.completed[0].outputs.A.image.assetIds[0] === 'a' && c.document.run.loop.completed[1].outputs.A.image.assetIds[0] === 'b', 'separate results retained');
    await c.continue(); check(submissions.length === 6, 'completed loop never repeats');
    const completedExample = structuredClone(c.document);
    await create('loop-recover', [loop(), gen('A')]); running = c.start('loop');
    await until(() => submissions.length === 1, 'recovery item one'); submissions[0].release();
    await until(() => submissions.length === 2, 'recovery item two');
    const checkpoint = structuredClone(c.document), oldIdentity = submissions[1].identity;
    const stopping = c.stop(); await until(() => cancelled.length === 1, 'cancel only active item'); submissions[1].release(); await Promise.all([running, stopping]);
    check(c.document.run.status === 'stopped' && c.document.run.loop.completed.length === 1, 'stop retains only completed items');
    await c.save(checkpoint); c = new CanvasWorkflowController('loop-recover'); await c.load();
    let ready = false;
    api.recentGenSessions = async () => [{ id: oldIdentity.jobId, status: ready ? 'done' : 'running', turns: [{ turn_key: oldIdentity.turnKey, images: ['b.png'] }] }];
    await c.continue(); check(c.document.run.status === 'waiting' && submissions.length === 2, 'resume queries original job');
    ready = true; await c.continue();
    check(c.document.run.status === 'done' && c.document.run.loop.completed.length === 2 && submissions.length === 2, 'recovery never replays');
    const base = window.snapshot().nodes[0];
    const cell = (id, text, image) => ({ id, text, bold: false, italic: false, align: 'left', ...(image ? { content_type: 'image', image_refs: [{ asset_id: image, token: '@图片1' }] } : {}) });
    const table = { ...base, id: 'loop-table', kind: 'note', assetId: null, role: null, threadId: null, payloadJson: JSON.stringify({ schema_version: 1, note_type: 'text', cells: [[cell('a1', '产品甲'), cell('a2', '', 'a')], [cell('b1', '产品乙'), cell('b2', '', 'b')]], text: '', member_ids: [] }) };
    await api.projectCanvasNodeCreate(table);
    const rows = { ...loop(), loopMode: 'rows', inputs: { text: [{ canvasNodeId: 'loop-table', cellId: '*text' }] } };
    const rowItems = workflowLoopRows(rows, [rows], [table]);
    check(rowItems[0].text === '产品甲' && rowItems[0].assetIds[0] === 'a' && rowItems[1].text === '产品乙' && rowItems[1].assetIds[0] === 'b', 'paired rows');
    let failSecond = true, requests = [], savedInputs = [];
    const replies = new Map();
    api.agentDsWorkflowStart = async (requestId, instruction, source) => { requests.push(requestId); const parsed = JSON.parse(source); savedInputs.push(parsed); replies.set(requestId, { schemaVersion: 1, requestId, ...(failSecond && parsed['引用文本 1'] === '产品乙' ? { error: '模拟失败' } : { text: `处理完成 ${parsed['引用文本 1']}` }) }); return { autoDelivered: true }; };
    api.agentDsWorkflowResult = async requestId => replies.get(requestId);
    const agent = { ...newWorkflowNode('agent', 420, 0, 'codex'), id: 'agent', prompt: '处理当前行', inputs: { text: [{ nodeId: 'loop', portId: 'text' }], image: [{ nodeId: 'loop', portId: 'image' }] } };
    await create('loop-rows', [rows, agent]); await c.start('loop');
    check(c.document.run.status === 'waiting' && c.document.run.loop.completed.length === 1 && c.document.run.loop.index === 1, 'failure pauses current row');
    check(c.isLocked('agent'), 'failed loop retains lock');
    check(savedInputs[0]['引用文本 1'] === '产品甲' && savedInputs[1]['引用文本 1'] === '产品乙', 'Agent receives one row');
    await api.projectCanvasNoteUpdate('loop-table', JSON.stringify({ schema_version: 1, note_type: 'text', cells: [[cell('a1', 'changed')]], text: 'changed', member_ids: [] }));
    c = new CanvasWorkflowController('loop-rows'); await c.load(); failSecond = false; await c.retryLoop(c.document.run.id);
    check(c.document.run.status === 'done' && requests.length === 3 && savedInputs[2]['引用文本 1'] === '产品乙', 'retry frozen failed row only');
    check(c.document.run.loop.completed[0].outputs.agent.text.text.includes('产品甲'), 'first result retained');
    // A produced table is resolved once, after its producer; loop iterations do not replay it.
    let sourceCalls = 0, bodyCalls = 0;
    api.agentDsWorkflowStart = async (requestId, instruction, source) => {
      const isSource = instruction === '制作表格';
      if (isSource) sourceCalls++; else bodyCalls++;
      replies.set(requestId, { schemaVersion: 1, requestId, text: isSource ? JSON.stringify({ format: 'bowerbird-table', columns: ['产品'], rows: [['甲'], ['乙']] }) : '完成' });
      return { autoDelivered: true };
    };
    const sourceAgent = { ...newWorkflowNode('agent', 0, 0, 'codex'), id: 'source', prompt: '制作表格' };
    const producedRows = { ...rows, inputs: { text: [{ nodeId: 'source', portId: 'text' }] } };
    const textAgent = { ...agent, inputs: { text: [{ nodeId: 'loop', portId: 'text' }] } };
    await create('loop-produced-rows', [sourceAgent, producedRows, textAgent]); await c.start('source');
    check(c.document.run.status === 'done' && sourceCalls === 1 && bodyCalls === 2, 'upstream runs once, body repeats for each produced row');
    check(c.document.run.loop.items[1].text === '产品：乙', 'structured table preserves column labels');
    // Human confirmation halts advancement to the next item.
    let confirmed = false;
    api.visualProfileGet = async () => ({ id: 'profile', status: confirmed ? 'confirmed' : 'draft', version: 1, summary: '规范' });
    const profile = { ...newWorkflowNode('visual-profile', 420, 0, 'codex'), id: 'profile', profileId: 'profile', inputs: { image: [{ nodeId: 'loop', portId: 'image' }] } };
    await create('loop-approval', [loop(), profile]); await c.start('loop');
    check(c.document.run.status === 'waiting' && c.document.run.loop.index === 0 && !c.document.run.loop.completed.length, 'approval pauses first item');
    confirmed = true; await c.continue(); check(c.document.run.status === 'done' && c.document.run.loop.completed.length === 2, 'confirmation resumes loop');
    // An ambiguous cloud submission must never become a fresh request through retry.
    await create('loop-unknown', [loop(), gen('A')]);
    const unknown = { id: 'unknown', startId: 'loop', threadId: 't', status: 'waiting', order: ['loop', 'A'], steps: { loop: { status: 'done' }, A: { status: 'failed', retrySafe: false } }, loop: { nodeId: 'loop', bodyIds: ['A'], index: 0, items: [{ text: '', assetIds: ['a'] }], completed: [] } };
    await c.save({ ...c.document, run: unknown, runs: [unknown] });
    let unknownRejected = false; try { await c.retryLoop('unknown'); } catch { unknownRejected = true; }
    check(unknownRejected && !submissions.length, 'unknown submissions require inspection, not automatic retry');
    await create('loop-empty', [{ ...loop(), inputs: {} }, gen('A')]);
    let rejected = false; try { await c.start('loop'); } catch { rejected = true; } check(rejected && !submissions.length, 'empty input rejects');
    const second = { ...loop(), id: 'second', inputs: { image: [{ nodeId: 'loop', portId: 'image' }] } };
    await create('loop-nested', [loop(), second, gen('A', 'second')]);
    rejected = false; try { await c.start('loop'); } catch { rejected = true; } check(rejected && !submissions.length, 'nested loops reject');
    const copied = cloneCanvasClipboard({ projectId: 'p', nodes: [], groups: [], items: [], selection: ['loop', 'A'], workflow: [loop(), gen('A')] }, 'p', 0, 0);
    check(copied.workflow[1].inputs.image[0].nodeId === copied.workflow[0].id && copied.workflow[0].id !== 'loop', 'copy remaps loop wiring');
    const { canvasWorkflowController } = await import('/src/lib/canvasWorkflowRuntime.ts');
    const host = canvasWorkflowController('p'), position = host.document.nodes[0];
    await host.save({ ...completedExample, nodes: completedExample.nodes.map((node, index) => ({ ...node, x: position.x + index * 400, y: position.y })) });
    return 'loop: UI/reload, sequential items, parallel branches, task identities, separate results, stop, recovery, paired rows, failed-row retry, frozen inputs, invalid/nested rejection and copy passed';
  }));
  await page.locator('.workflow-loop-results > summary').click();
  await page.locator('.workflow-loop-results > details > summary').first().click();
  await page.locator('.workflow-loop-results img').first().waitFor();
  assert.equal(await page.locator('.workflow-loop-results > details').count(), 2);
  await page.screenshot({ path: '.tmp/workflow/loop-results.png' });
  assert.deepEqual(errors, []);
} finally { await browser.close(); await server.close(); }
