import assert from 'node:assert/strict';
import { mkdir } from 'node:fs/promises';
import { createServer } from 'vite';
import { chromium } from '../../html-renderer/node_modules/playwright/index.mjs';
const server=await createServer({configFile:false,root:process.cwd(),server:{host:'127.0.0.1',port:1583,strictPort:true,hmr:false,watch:null}});
await server.listen();
const browser=await chromium.launch({channel:'chrome',headless:true});
const page=await browser.newPage({viewport:{width:1800,height:1200}});
page.setDefaultTimeout(15000);
const errors=[];page.on('pageerror',e=>errors.push(e.message));
try {
  await page.goto('http://127.0.0.1:1583/scripts/fixtures/canvas-reference/preview.html');
  await page.locator('[data-canvas-node-id="old"]').waitFor();
  await page.evaluate(()=>{const snapshot=window.snapshot();snapshot.nodes=snapshot.nodes.filter(n=>n.id!=='far');sessionStorage.setItem('reference-fixture',JSON.stringify(snapshot));});
  await page.reload();await page.locator('[data-canvas-node-id="old"]').waitFor();
  await page.evaluate(async()=>{
    const {api}=await import('/src/lib/api.ts');
    const {useStore}=await import('/src/store.ts');
    window.profileDrafts={};window.extracts=0;window.generatedProfiles=[];
    useStore.setState({cloudAuth:{user_id:'test',logged_in:true,cloud_available:true},cloudEntitlement:{user_id:'test',balances:{daily:100,sub:0,topup:0},policy:{can_use_visual_profiles:true}}});
    api.visualProfileInputPreview=async()=>[];
    api.visualProfileExtractInputs=async(scope,name,assets,requirements)=>{
      const id='profile-'+(++window.extracts);
      const profile={id,folderId:'workflow:'+scope,name,version:window.extracts,status:'draft',extractor:'cloud_model',summary:'蓝色与宽松留白',sourceCount:assets.length,sourceAssetIds:assets,sourceRequirements:requirements,sourceScopeHash:'hash',rules:[{category:'palette',value:'使用蓝色',polarity:'must',confidence:0,supportingAssetIds:[],opposingAssetIds:[],confirmedByUser:false}],conflicts:[],contentThemes:[],candidateDirections:[],ruleCount:1,createdAt:1};
      window.profileDrafts[id]=profile;return profile;
    };
    api.visualProfileGet=async id=>structuredClone(window.profileDrafts[id]);
    api.visualProfileList=async folder=>Object.values(window.profileDrafts).filter(p=>!folder||p.folderId===folder);
    api.visualProfilePreview=async()=>{throw 'No collection: workflow scope';};
    api.visualProfileConfirm=async id=>{window.profileDrafts[id].status='confirmed';return structuredClone(window.profileDrafts[id]);};
    api.localAgentFindAssetId=async()=> 'existing';
    useStore.setState({startGeneration:async(...args)=>{
      window.generatedProfiles.push(args[8]);
      useStore.setState(s=>({genJobs:{...s.genJobs,[args[12].jobId]:{turns:[{images:['out.png']}]} }}));
      return {accepted:true};
    }});
  });
  await page.getByRole('button',{name:'新增视觉规范卡片',exact:true}).click();
  const profile=page.locator('.workflow-card.is-visual-profile');
  await profile.getByLabel('规范名称').fill('蓝色系列');
  await profile.getByLabel('视觉要求').fill('使用蓝色，宽松留白');
  assert.equal(await profile.getByLabel('输入：文本',{exact:true}).count(),1);
  assert.equal(await profile.getByLabel('输入：图片',{exact:true}).count(),1);
  assert.equal(await profile.getByLabel('输出：视觉规范',{exact:true}).count(),1);
  await page.getByRole('button',{name:'新增生成卡片',exact:true}).click();
  const gen=page.locator('.workflow-card.is-generation');
  await gen.getByLabel('卡片指令').fill('画一张产品海报');
  await page.evaluate(async()=>{const {canvasWorkflowController}=await import('/src/lib/canvasWorkflowRuntime.ts');const c=canvasWorkflowController('p');await c.edit(c.document.nodes.map((n,i)=>({...n,x:700+i*440,y:240})));});
  await page.getByRole('button',{name:'适应内容',exact:true}).click();
  await profile.getByLabel('输出：视觉规范',{exact:true}).click();
  await gen.getByLabel('输入：视觉规范',{exact:true}).click();
  await page.getByRole('button',{name:'发条触发器',exact:true}).click();
  await profile.locator('header strong').click();
  await profile.getByLabel('上发条，运行工作流',{exact:true}).click();
  await page.getByRole('button',{name:'保存规范',exact:true}).waitFor();
  assert.equal(await page.evaluate(()=>window.generatedProfiles.length),0);
  await page.getByText('提炼时的文字要求',{exact:true}).click();
  await page.getByRole('button',{name:'保存规范',exact:true}).click();
  await profile.getByLabel('继续工作流',{exact:true}).click();
  await page.waitForFunction(()=>window.generatedProfiles.length===1);
  assert.deepEqual(await page.evaluate(()=>window.generatedProfiles),['profile-1']);
  await page.waitForFunction(async()=>{const {canvasWorkflowController}=await import('/src/lib/canvasWorkflowRuntime.ts');return canvasWorkflowController('p').document.run.status==='done';});
  await profile.getByLabel('上发条，运行工作流',{exact:true}).click();
  await page.waitForFunction(()=>window.generatedProfiles.length===2);
  assert.equal(await page.evaluate(()=>window.extracts),1,'unchanged inputs reuse confirmed profile');
  await page.waitForFunction(async()=>{const {canvasWorkflowController}=await import('/src/lib/canvasWorkflowRuntime.ts');return canvasWorkflowController('p').document.run.status==='done';});
  await profile.getByLabel('视觉要求').fill('使用蓝色，增加顶部留白');
  await profile.getByLabel('上发条，运行工作流',{exact:true}).click();
  await page.getByRole('button',{name:'保存规范',exact:true}).waitFor();
  assert.equal(await page.evaluate(()=>window.extracts),2,'changed input creates new draft');
  await page.getByRole('button',{name:'保存规范',exact:true}).click();
  await profile.getByLabel('继续工作流',{exact:true}).click();
  await page.waitForFunction(()=>window.generatedProfiles.length===3);
  await page.waitForFunction(async()=>{const {canvasWorkflowController}=await import('/src/lib/canvasWorkflowRuntime.ts');return canvasWorkflowController('p').document.run.status==='done';});
  await profile.getByLabel('视觉规范来源').selectOption('profile-1');
  await profile.getByLabel('上发条，运行工作流',{exact:true}).click();
  await page.waitForFunction(()=>window.generatedProfiles.length===4);
  assert.equal(await page.evaluate(()=>window.extracts),2,'existing profile does not extract');
  assert.equal(await page.evaluate(()=>window.generatedProfiles.at(-1)),'profile-1');
  await page.waitForFunction(async()=>{const {canvasWorkflowController}=await import('/src/lib/canvasWorkflowRuntime.ts');return canvasWorkflowController('p').document.run.status==='done';});
  // Arrange only the synthetic workspace for a readable screenshot.
  await page.evaluate(async()=>{const {canvasWorkflowController}=await import('/src/lib/canvasWorkflowRuntime.ts');const c=canvasWorkflowController('p');await c.edit(c.document.nodes.map((n,i)=>({...n,x:800+i*440,y:160})));});
  await mkdir('.tmp/workflow',{recursive:true});await page.screenshot({path:'.tmp/workflow/visual-profile.png'});
  await page.evaluate(async()=>{
    const {api}=await import('/src/lib/api.ts');
    const {CanvasWorkflowController}=await import('/src/lib/canvasWorkflowRuntime.ts');
    const {newWorkflowNode,workflowConnectionError}=await import('/src/lib/canvasWorkflow.ts');
    const {useStore}=await import('/src/store.ts');
    const check=(v,m)=>{if(!v)throw Error(m);};
    const make=async(name,nodes)=>{const c=new CanvasWorkflowController(name);await c.load();await c.edit(nodes);return c;};
    const selected={...newWorkflowNode('visual-profile',0,0,'codex'),id:'v',profileId:'profile-1'};
    const skill={...newWorkflowNode('skill',400,0,'codex'),id:'s',prompt:'制作海报',inputs:{'visual-profile':[{nodeId:'v',portId:'visual-profile'}]}};
    check(workflowConnectionError([selected,skill],'v','visual-profile','s','text')!==null,'profile cannot become text wire');
    useStore.setState({cloudEntitlement:{user_id:'test',is_test_account:true,balances:{daily:100,sub:0,topup:0},policy:{can_use_agent_runs:true,max_parallel_agent_runs:1,allowed_agent_skills:['bowerbird-unified-agent'],agent_budget_options:['controlled-standard']}}});
    let received;
    api.cloudAgentStart=async request=>{received=request.visualProfileId;return {runId:'skill-profile',status:'awaiting_approval',snapshot:{run:{},artifacts:[],events:[]}};};
    const agent=await make('profile-skill',[selected,skill]);await agent.start('v');
    check(received==='profile-1','skill receives selected profile ID');
    api.cloudAgentCancel=async()=>{};await agent.stop();
    // Images use current brand observations, then the same approval boundary.
    const imageNode={...newWorkflowNode('visual-profile',0,0,'codex'),id:'image',inputs:{image:[{assetId:'existing'}]},prompt:'保留配色'};
    let described=false;
    api.visualProfileInputPreview=async(ids,requirements)=>{check(ids[0]==='existing','explicit image source');check(requirements==='保留配色','text requirements reach the capability preflight');return ['existing'];};
    api.describeAsset=async(_id,instruction)=>{check(instruction==='bowerbird:brand-visual-observation:v2','brand observation protocol');described=true;return 'analysis';};
    const mixed=await make('profile-mixed',[imageNode]);await mixed.start('image');
    check(described&&mixed.document.run.status==='waiting','images are observed and draft pauses');await mixed.stop();
    api.visualProfileInputPreview=async(ids,requirements)=>{check(ids[0]==='existing'&&requirements==='','image-only preview does not require text capability');return [];};
    const imagesOnly=await make('profile-images-only',[{...imageNode,prompt:''}]);await imagesOnly.start('image');
    check(imagesOnly.document.run.status==='waiting','image-only extraction produces a draft');await imagesOnly.stop();
    const extracts=window.extracts;
    api.visualProfileInputPreview=async()=>{throw Error('new server required');};
    const blocked=await make('profile-blocked',[imageNode]);await blocked.start('image');
    check(window.extracts===extracts,'old server prevents extraction');await blocked.stop();
    window.profileDrafts['profile-1'].status='archived';
    const archived=await make('profile-archived',[selected]);await archived.start('v');
    check(archived.document.run.status==='failed'&&!archived.document.nodes[0].outputs['visual-profile'],'archived profile has no output');
  });
  assert.deepEqual(errors,[]);
  console.log('visual profile workflow: typed ports, text draft, real confirmation UI, downstream generation, cache, changed input and existing profile passed');
} catch(error) {console.log('Page errors:',errors);await mkdir('.tmp/workflow',{recursive:true});await page.screenshot({path:'.tmp/workflow/profile-failure.png'});throw error;}
finally {await browser.close();await server.close();}

