import assert from "node:assert/strict";
import { mkdir } from "node:fs/promises";
import { createServer } from "vite";
import { chromium } from "../../html-renderer/node_modules/playwright/index.mjs";
const server = await createServer({ server: { host: "127.0.0.1", port: 1577, strictPort: true, hmr: false, watch: null } });
await server.listen();
const browser = await chromium.launch({ channel: "chrome", headless: true });
const page = await browser.newPage({ viewport: { width: 1550, height: 1050 } });
const errors = []; page.on("pageerror", error => errors.push(error.message));
const dialog = page.getByRole("dialog", { name: "分层编辑" });
try {
  await page.goto("http://127.0.0.1:1577/scripts/fixtures/layers/preview.html");
  await page.getByRole("button", { name: "打开右键菜单", exact: true }).click();
  await page.getByRole("menuitem", { name: "分层编辑", exact: true }).click();
  await dialog.getByRole("button", { name: "开始拆分 · 20 积分/次" }).waitFor();
  await dialog.getByLabel("拆分要求").fill("拆出标题文字与圆形装饰");
  // Submission response loss is recovered using the persisted idempotency key.
  await page.evaluate(() => { window.submitDisconnect = true; });
  await dialog.getByRole("button", { name: "开始拆分 · 20 积分/次" }).click();
  await dialog.getByRole("button", { name: "继续取回原任务" }).waitFor();
  const request = await page.evaluate(() => window.saved().pending.request);
  assert.equal(request.layer_options.operation, "decompose");
  assert.equal(request.reference_images.length, 1);
  await page.reload();
  await page.getByRole("button", { name: "打开分层编辑", exact: true }).click();
  await dialog.getByRole("button", { name: "继续取回原任务" }).click();
  await dialog.getByLabel("图层名称").waitFor();
  assert.equal(await page.evaluate(() => window.calls.filter(call => call.command === "layer_cloud_request" && !call.args.request.action).length), 0, "recovery must query the existing job, never create again");
  assert.equal(await page.evaluate(() => window.saved().pending), null);
  await mkdir(".tmp", { recursive: true });
  await dialog.getByRole("button", { name: "保存图层工程", exact: true }).click();
  await page.screenshot({ path: ".tmp/layer-editor-initial.png" });
  const stage = dialog.locator(".layer-stage"), title = stage.locator('[data-layer-id="title"]');
  let bounds = await stage.boundingBox(); assert.ok(Math.abs(bounds.width / bounds.height - 1024 / 768) < 0.01);
  const before = +await dialog.getByLabel("图层 X", { exact: true }).inputValue();
  const box = await title.boundingBox();
  await page.mouse.move(box.x + box.width / 2, box.y + box.height / 2); await page.mouse.down(); await page.mouse.move(box.x + box.width / 2 + 40, box.y + box.height / 2 + 30, { steps: 6 }); await page.mouse.up();
  assert.ok(+await dialog.getByLabel("图层 X", { exact: true }).inputValue() > before + 30);
  await dialog.getByRole("button", { name: "撤销", exact: true }).click();
  assert.equal(+await dialog.getByLabel("图层 X", { exact: true }).inputValue(), before);
  const handle = await dialog.getByLabel("等比缩放图层").boundingBox();
  await page.mouse.move(handle.x + 5, handle.y + 5); await page.mouse.down(); await page.mouse.move(handle.x - 60, handle.y + 5, { steps: 6 }); await page.mouse.up();
  const width = +await dialog.getByLabel("图层宽度").inputValue();
  const height = +await dialog.getByLabel("图层高度").inputValue();
  assert.ok(width < 700); assert.ok(Math.abs(width / height - 7) < 0.08);
  await dialog.getByRole("button", { name: "下移一层" }).click();
  assert.equal(await stage.locator(".layer-object").last().getAttribute("data-layer-id"), "circle");
  await dialog.getByRole("button", { name: "隐藏圆形装饰" }).click();
  assert.equal(await stage.locator('[data-layer-id="circle"]').count(), 0);
  await dialog.getByLabel("不透明度", { exact: true }).fill("55");
  await dialog.getByRole("button", { name: "保存图层工程", exact: true }).click();
  await page.waitForFunction(() => window.saved().document.layers[1].opacity === .55);
  await dialog.getByRole("button", { name: "关闭", exact: true }).click();
  await page.getByRole("button", { name: "打开分层编辑", exact: true }).click();
  await dialog.getByLabel("图层名称").waitFor();
  await dialog.getByRole("button", { name: "标题文字", exact: true }).click();
  assert.equal(await dialog.getByLabel("不透明度", { exact: true }).inputValue(), "55");
  await dialog.getByLabel("图层 X", { exact: true }).fill("220");
  await page.evaluate(() => { window.failSave = true; });
  await dialog.getByRole("button", { name: "保存图层工程", exact: true }).click();
  await dialog.getByRole("alert").waitFor();
  assert.equal(await dialog.getByLabel("图层 X", { exact: true }).inputValue(), "220", "save failure retains edits");
  await page.evaluate(() => { window.failSave = false; window.store.setState({ activeProjectId: "project-later" }); });
  await dialog.getByRole("button", { name: "合成图片入库", exact: true }).click();
  await page.waitForFunction(() => window.exports.length === 1);
  const exported = await page.evaluate(() => window.exports[0]);
  assert.equal(exported.projectId, "project-original", "export uses the project frozen when opened");
  const mismatch = await page.evaluate(async output => {
    const { renderLayerDocument } = await import("/src/lib/layerDocument.ts");
    return await renderLayerDocument(output.document) !== output.dataUrl;
  }, exported);
  assert.equal(mismatch, false, "export pixels must match the edited composition");
  await dialog.getByLabel("图层修改要求").fill("把文字改为圆形装饰");
  await dialog.getByRole("button", { name: "修改选中图层 · 20 积分/次" }).click();
  await page.waitForFunction(() => window.saved().pending === null && window.saved().document.layers[1].dataUrl === window.documentFixture.layers[1].dataUrl);
  const edited = await page.evaluate(() => window.saved().document.layers[1]);
  assert.equal(edited.x, 220); assert.equal(edited.opacity, .55);
  await dialog.getByRole("button", { name: "保存图层工程", exact: true }).click();
  await page.screenshot({ path: ".tmp/layer-editor.png" });
  await dialog.getByRole("button", { name: "关闭", exact: true }).click();
  await page.evaluate(() => { sessionStorage.clear(); });
  await page.reload();
  await page.evaluate(() => { window.enabled = false; });
  await page.getByRole("button", { name: "打开分层编辑", exact: true }).click();
  await dialog.getByRole("button", { name: "拆分服务待开放" }).waitFor();
  assert.equal(await dialog.getByRole("button", { name: "拆分服务待开放" }).isDisabled(), true);
  assert.equal(await page.evaluate(() => window.calls.filter(call => call.command === "layer_cloud_request" && !call.args.request.action).length), 0);
  assert.deepEqual(errors, []);
  console.log("PASS: menu, persisted recovery, no repeat submission, drag/resize/undo/order/visibility/opacity, reopen, save failure, frozen project, PNG composition, alpha-layer AI replacement");
} finally { await browser.close(); await server.close(); }
