import assert from "node:assert/strict";
import { createServer } from "vite";
import { chromium } from "../../html-renderer/node_modules/playwright/index.mjs";
const server = await createServer({ server: { host: "127.0.0.1", port: 1583, strictPort: true, hmr: false, watch: null } });
await server.listen();
const browser = await chromium.launch({ channel: "chrome", headless: true });
const page = await browser.newPage({ viewport: { width: 1500, height: 1050 } });
const errors = []; page.on("pageerror", error => errors.push(error.message));
const dialog = page.getByRole("dialog", { name: "分层编辑", exact: true });
const open = async () => { await page.getByRole("button", { name: "打开分层编辑", exact: true }).click(); await dialog.getByLabel("图层名称").waitFor(); };
const exit = async () => { await dialog.getByRole("button", { name: "暂时退出", exact: true }).click(); await dialog.waitFor({ state: "hidden" }); };
try {
  await page.goto("http://127.0.0.1:1583/scripts/fixtures/layers/preview.html");
  await page.evaluate(() => sessionStorage.setItem("layer-workspace", JSON.stringify({ document: window.documentFixture, pending: null })));
  await page.reload(); await open();
  assert.equal(await dialog.getByRole("button", { name: "关闭", exact: true }).count(), 0);
  await dialog.getByLabel("图层 X", { exact: true }).fill("220");
  await dialog.locator('[data-layer-id="title"]').dblclick();
  const confirm = page.getByRole("dialog", { name: "转为可编辑文字", exact: true });
  await confirm.getByRole("tab", { name: "创建空白文字对象" }).click();
  await confirm.getByRole("button", { name: "确认", exact: true }).click();
  await dialog.getByLabel("画布文字内容").fill("自动保存的文字");
  await dialog.locator(".app-modal-header").getByText("有未保存的修改", { exact: true }).waitFor();
  assert.equal(await dialog.locator(".app-modal-footer").getByText("有未保存的修改").count(), 0);
  await exit();
  const saved = await page.evaluate(() => window.saved());
  assert.equal(saved.document.layers[2].text.content, "自动保存的文字");
  assert.equal(saved.history.documents.length, 3);
  assert.deepEqual(saved.history.images, [], "unchanged images reuse current pixels instead of duplicating them per undo step");
  await page.reload(); await open();
  // Undo survives a full reload: text, conversion, then position.
  await dialog.getByLabel("图层画布").focus();
  await page.keyboard.press("Control+z");
  assert.equal(await dialog.getByLabel("文字内容", { exact: true }).inputValue(), "");
  await page.keyboard.press("Control+z");
  assert.equal(await dialog.locator('[data-layer-id="title"] img').count(), 1);
  await page.keyboard.press("Control+z");
  assert.equal(await dialog.getByLabel("图层 X", { exact: true }).inputValue(), "140");
  assert.equal(await dialog.getByRole("button", { name: "撤销", exact: true }).isDisabled(), true);
  await exit();
  await open();
  const baseline = await page.evaluate(() => window.saved());
  await dialog.getByLabel("图层 X", { exact: true }).fill("333");
  await dialog.getByRole("button", { name: "舍弃修改", exact: true }).click();
  await dialog.waitFor({ state: "hidden" });
  assert.deepEqual(await page.evaluate(() => window.saved()), baseline, "discard must not write changes or undo history");
  await open();
  assert.equal(await dialog.getByLabel("图层 X", { exact: true }).inputValue(), "140");
  await dialog.getByLabel("图层 X", { exact: true }).fill("444");
  await page.evaluate(() => { window.failSave = true; });
  await dialog.getByRole("button", { name: "暂时退出", exact: true }).click();
  await dialog.getByRole("alert").filter({ hasText: "自动保存失败" }).waitFor();
  assert.equal(await dialog.getByLabel("图层 X", { exact: true }).inputValue(), "444");
  assert.deepEqual(await page.evaluate(() => window.saved()), baseline);
  await page.evaluate(() => { window.failSave = false; });
  // Escape follows the same save-and-exit path.
  await page.keyboard.press("Escape"); await dialog.waitFor({ state: "hidden" });
  await page.reload(); await open();
  assert.equal(await dialog.getByLabel("图层 X", { exact: true }).inputValue(), "444");
  await page.keyboard.press("Control+z");
  assert.equal(await dialog.getByLabel("图层 X", { exact: true }).inputValue(), "140");
  // Exiting mid-drag must retain the drag's starting point as an undo step.
  await page.evaluate(() => Promise.all(document.getAnimations().filter(a => a.effect?.getTiming().iterations !== Infinity).map(a => a.finished)));
  const box = await dialog.locator('[data-layer-id="title"]').boundingBox();
  await page.mouse.move(box.x + box.width / 2, box.y + box.height / 2); await page.mouse.down();
  await page.mouse.move(box.x + box.width / 2 + 40, box.y + box.height / 2 + 20, { steps: 4 });
  await page.keyboard.press("Escape"); await dialog.waitFor({ state: "hidden" }); await page.mouse.up();
  assert.ok(await page.evaluate(() => window.saved().document.layers[2].x > 140));
  await page.reload(); await open(); await page.keyboard.press("Control+z");
  assert.equal(await dialog.getByLabel("图层 X", { exact: true }).inputValue(), "140");
  // AI replacement preserves the earlier raster in the deduplicated history pool.
  await dialog.getByLabel("图层修改要求").fill("修改图层");
  await page.evaluate(() => { window.pendingBusy = true; });
  await dialog.getByRole("button", { name: "修改选中图层" }).click();
  await dialog.getByRole("button", { name: "停止等待" }).waitFor();
  await exit();
  assert.ok(await page.evaluate(() => window.saved().pending));
  await page.reload(); await open();
  await dialog.getByRole("button", { name: "继续取回原任务" }).click();
  await page.waitForFunction(() => window.saved().pending === null);
  await exit(); await page.reload(); await open();
  assert.equal(await page.evaluate(() => window.saved().history.images.length), 1);
  await page.keyboard.press("Control+z");
  assert.equal(await dialog.locator('[data-layer-id="title"] img').getAttribute("src"), await page.evaluate(() => window.documentFixture.layers[2].dataUrl));
  assert.equal(await page.evaluate(() => window.calls.filter(c => c.command === "layer_cloud_request" && !c.args.request.action).length), 0);
  await page.evaluate(() => Promise.all(document.getAnimations().filter(a => a.effect?.getTiming().iterations !== Infinity).map(a => a.finished)));
  await page.screenshot({ path: ".tmp/layer-history.png" });
  assert.deepEqual(errors, []);
  console.log("PASS autosave exit/reload undo, deduplicated pixels, text/geometry/raster history, discard, failure retention, Escape, header actions and pending cloud exit/recovery");
} finally { await browser.close(); await server.close(); }
