import assert from "node:assert/strict";
import { mkdir } from "node:fs/promises";
import { createServer } from "vite";
import { createRequire } from "node:module";
import { fileURLToPath } from "node:url";
const requireRenderer = createRequire(new URL("../../html-renderer/package.json", import.meta.url));
const { chromium } = process.env.BOWERBIRD_PLAYWRIGHT_MODULE ? await import(process.env.BOWERBIRD_PLAYWRIGHT_MODULE) : requireRenderer("playwright");
const server = await createServer({ root: fileURLToPath(new URL("..", import.meta.url)), server: { host: "127.0.0.1", port: 1456, strictPort: true } });
await server.listen();
const browser = await chromium.launch({ channel: "chrome", headless: true });
try {
  const page = await browser.newPage({ viewport: { width: 1050, height: 950 } });
  const errors = []; page.on("pageerror", e => errors.push(e.message));
  await page.route("**/*", route => new URL(route.request().url()).hostname === "127.0.0.1" ? route.continue() : route.abort());
  await page.goto("http://127.0.0.1:1456/scripts/fixtures/local-classification/preview.html");
  const dialog = page.getByRole("dialog");
  await dialog.getByRole("button", { name: "下载本地模型" }).click();
  await dialog.getByRole("button", { name: "停止", exact: true }).waitFor();
  await page.keyboard.press("Escape");
  await page.getByRole("button", { name: "打开本地分类" }).click();
  await dialog.getByRole("button", { name: "停止", exact: true }).click();
  assert.equal(await page.evaluate(() => window.calls.filter(c => c.command === "local_classification_start").length), 1);
  await page.evaluate(() => window.classificationStatus.installed = true);
  await dialog.getByRole("button", { name: "识别未处理素材" }).waitFor();
  await page.evaluate(() => window.classificationStatus.acceleration = "GPU · NVIDIA GeForce RTX 4070 Ti SUPER（CUDA）");
  await dialog.getByText("GPU · NVIDIA GeForce RTX 4070 Ti SUPER（CUDA）", { exact: true }).waitFor();
  await page.evaluate(() => window.classificationStatus.acceleration = "CPU · GPU 驱动不可用，已回退 CPU");
  await dialog.getByText("CPU · GPU 驱动不可用，已回退 CPU", { exact: true }).waitFor();
  await dialog.getByLabel("标签名称").fill("水彩植物");
  await dialog.getByLabel("分类说明").fill("有透明水彩笔触的植物插画");
  await dialog.getByRole("button", { name: "保存并寻找匹配素材" }).evaluate(el => { el.click(); el.click(); });
  await dialog.getByText("#水彩植物", { exact: true }).waitFor();
  assert.equal(await page.evaluate(() => window.calls.filter(c => c.command === "local_classification_save_label").length), 1);
  const start = await page.evaluate(() => window.calls.filter(c => c.command === "local_classification_start").at(-1));
  assert.equal(start.args.tagId, "label-0");
  await dialog.getByRole("button", { name: "停止", exact: true }).click();
  await dialog.getByRole("button", { name: "加入所选 2 张作为示例" }).click();
  assert.equal(await page.evaluate(() => window.calls.filter(c => c.command === "local_classification_example").at(-1).args.positive), true);
  await dialog.getByRole("button", { name: "排除所选素材", exact: true }).click();
  assert.equal(await page.evaluate(() => window.calls.filter(c => c.command === "local_classification_example").at(-1).args.positive), false);
  await dialog.getByLabel("Jev API Key").fill("tsk-test");
  await dialog.getByRole("button", { name: "保存云端校验设置" }).click();
  assert.equal(await page.evaluate(() => window.calls.filter(c => c.command === "update_settings").at(-1).args.settings.jev_api_key), "tsk-test");
  assert.equal(await page.evaluate(() => window.calls.filter(c => c.command === "update_settings").at(-1).args.settings.jev_verify_enabled), false);
  await dialog.getByText("向量精确匹配（jina-clip-v2）", { exact: true }).waitFor();
  await dialog.getByRole("button", { name: "下载向量匹配模型" }).click();
  assert.equal(await page.evaluate(() => window.calls.filter(c => c.command === "local_classification_vector_install").length), 1);
  await page.evaluate(() => { window.classificationStatus.vector_installed = true; window.classificationStatus.busy = false; });
  await dialog.getByText("安装后标签匹配改用图像与文本的向量相似度判断", { exact: false }).waitFor();
  await dialog.getByRole("button", { name: "卸载向量匹配模型" }).click();
  assert.equal(await page.evaluate(() => window.calls.filter(c => c.command === "local_classification_vector_uninstall").length), 1);
  await dialog.getByRole("button", { name: "下载向量匹配模型" }).waitFor();
  await page.evaluate(() => window.failure = "local_classification_start");
  await dialog.getByRole("button", { name: "寻找匹配", exact: true }).click();
  await dialog.getByRole("alert").waitFor();
  await page.waitForFunction(() => !document.querySelector('input[aria-label="标签名称"]')?.disabled && ![...document.querySelectorAll('button')].find(b => b.textContent === '寻找匹配')?.disabled);
  await mkdir(".tmp", { recursive: true });
  await page.screenshot({ path: ".tmp/local-classification-dark.png" });
  await page.evaluate(() => document.documentElement.dataset.theme = "light");
  await page.waitForTimeout(350);
  await page.setViewportSize({ width: 540, height: 900 });
  await page.screenshot({ path: ".tmp/local-classification-light-narrow.png" });
  assert.equal(await dialog.evaluate(el => el.scrollWidth > el.clientWidth + 1), false);
  await page.evaluate(() => {
    window.classificationStatus.installed = false;
    window.classificationStatus.supported = false;
  });
  await dialog.getByText("此模型包支持 Windows x64、macOS 13.3+（Intel / Apple Silicon）。", { exact: true }).waitFor();
  assert.equal(await dialog.getByRole("button", { name: "下载本地模型" }).isDisabled(), true);
  assert.deepEqual(errors, []);
  console.log("local classification UI: install/stop/reopen/create/match/examples/errors/dark/light/narrow passed");
} finally { await browser.close(); await server.close(); }
