import assert from 'node:assert/strict';
import { mkdir, readFile } from 'node:fs/promises';
import { createServer } from 'vite';
import { chromium } from '../../html-renderer/node_modules/playwright/index.mjs';
const server = await createServer({ server: { host:'127.0.0.1', port:1561, strictPort:true, hmr:false, watch:null } });
await server.listen();
const browser = await chromium.launch({ channel:'chrome', headless:true });
const page = await browser.newPage({ viewport:{width:1600,height:1000} });
page.setDefaultTimeout(10000);
const errors = [];
page.on('pageerror', e => errors.push(e.message));
const button = name => page.getByRole('button', {name,exact:true});
const next = () => button('下一步');
async function at(scene) {
  await page.waitForFunction(async scene => {
    const {ONBOARDING_ROUTES} = await import('/src/lib/onboardingRoutes.ts');
    const g = window.lesson.getState().guide;
    return g.role && ONBOARDING_ROUTES[g.role][g.sessions[g.role].step].scene === scene;
  }, scene);
}
async function ready() { await page.waitForFunction(() => { const g=window.lesson.getState().guide; return g.sessions[g.role].ready; }); }
async function notReady() {
  await page.waitForTimeout(400);
  assert.equal(await page.evaluate(() => { const g=window.lesson.getState().guide; return g.sessions[g.role].ready; }),false);
}
async function pick(label) {
  await page.locator('[data-import-trigger]').click();
  await page.getByRole('menuitem',{name:label,exact:true}).click();
}
async function fakeResult(media, count, overrides = {}) {
  await page.evaluate(({media,count,overrides}) => {
    const state=window.store.getState(), g=window.lesson.getState().guide, s=g.sessions[g.role];
    const id=overrides.id ?? crypto.randomUUID();
    const job={id, projectId:s.projectId, media, createdAt:Date.now(), running:false, provider:'jimeng', turns:[{
      id:1, startedAt:Date.now(), media, prompt:'fixture result', refAssets:s.annotationAssetId?[{id:s.annotationAssetId}]:[], images:Array.from({length:count},(_,i)=>'fixture-result-'+id+'-'+i), error:null
    }], ...overrides};
    window.store.setState({genJobs:{...state.genJobs,[id]:job}});
  }, {media,count,overrides});
}
try {
  // Run the exact native injection against a page with a top-layer login dialog.
  const remote=await browser.newPage();
  await remote.setContent('<button id="under">网页按钮</button><dialog><button>登录</button></dialog>');
  await remote.locator('dialog').evaluate(el=>el.showModal());
  const dimScript=await readFile('src-tauri/src/commands/source_browser_spotlight.js','utf8');
  await remote.evaluate(dimScript.replaceAll('__BOWERBIRD_DIMMED__','true'));
  assert.equal(await remote.locator('#bowerbird-onboarding-shade').evaluate(el=>el.matches(':popover-open')),true);
  assert.equal(await remote.locator('#bowerbird-onboarding-shade').evaluate(el=>getComputedStyle(el).backgroundColor),'rgba(0, 0, 0, 0.56)');
  await remote.evaluate(dimScript.replaceAll('__BOWERBIRD_DIMMED__','true'));
  assert.equal(await remote.locator('#bowerbird-onboarding-shade').count(),1);
  await remote.getByRole('button',{name:'登录',exact:true}).click();
  await remote.evaluate(dimScript.replaceAll('__BOWERBIRD_DIMMED__','false'));
  assert.equal(await remote.locator('#bowerbird-onboarding-shade').count(),0);
  await remote.close();
  await page.goto('http://127.0.0.1:1561/scripts/fixtures/onboarding/preview.html');
  await page.getByRole('heading',{name:'请选择你的身份',exact:true}).waitFor();
  for (const name of ['设计师','市场运营','视频编导']) await button('我是'+name).waitFor();
  assert.equal(await page.getByText(/操作示意|继续原来的实操引导|开始这条路线|用示例实际做一次/).count(),0);
  await mkdir('.tmp',{recursive:true});
  await page.screenshot({path:'.tmp/onboarding-practice-welcome.png'});
  await button('我是设计师').click();
  await at('create-project'); await notReady();
  assert.equal(await page.evaluate(()=>window.store.getState().activeProjectId),null);
  assert.equal(await page.locator('.canvas-workspace').count(),0);
  await page.locator('[data-spotlight-hole]').waitFor({state:'attached'});
  async function spotlightContains(selector) {
    await page.waitForFunction(selector=>{
      const hole=document.querySelector('[data-spotlight-hole]'), target=document.querySelector(selector);
      if (!hole || !target) return false;
      const x=Number(hole.getAttribute('x')),y=Number(hole.getAttribute('y')),r=target.getBoundingClientRect();
      return x<=r.left && y<=r.top && x+Number(hole.getAttribute('width'))>=r.right && y+Number(hole.getAttribute('height'))>=r.bottom;
    },selector);
    const fits=await page.locator('[data-spotlight-hole]').evaluate((hole,selector)=>{
      const left=Number(hole.getAttribute('x')),top=Number(hole.getAttribute('y'));
      const h={left,top,right:left+Number(hole.getAttribute('width')),bottom:top+Number(hole.getAttribute('height'))},r=document.querySelector(selector).getBoundingClientRect();
      return h.left<=r.left && h.top<=r.top && h.right>=r.right && h.bottom>=r.bottom;
    },selector);
    assert.equal(fits,true);
    assert.equal(await page.locator('.onboarding-target').count(),0);
  }
  await spotlightContains('[data-tour=new-creation]');
  assert.equal(await button('上一步').isDisabled(),true);
  assert.equal(await page.locator('.onboarding-spotlight-card').evaluate(el=>Math.round(el.getBoundingClientRect().width)),416);
  assert.equal(await page.locator('.onboarding-step-copy').evaluate(el=>getComputedStyle(el).fontSize),'16px');
  await page.screenshot({path:'.tmp/onboarding-designer-create.png'});
  await button('稍后继续').click();
  await page.waitForFunction(()=>{
    const bubble=document.querySelector('.onboarding-resume')?.getBoundingClientRect();
    const status=document.querySelector('[data-tour=app-status]')?.getBoundingClientRect();
    return bubble && status && bubble.top>=status.bottom && bubble.top<=status.bottom+20 && innerWidth-bubble.right<=20;
  });
  await page.reload();
  await button('继续入门引导').click(); await button('我是设计师').click(); await at('create-project');
  await button('新建创作').click(); await at('folder'); await notReady();
  await page.locator('.canvas-workspace[aria-busy="false"]').waitFor();
  const projectId=await page.evaluate(()=>window.store.getState().activeProjectId);
  assert.notEqual(projectId,'p');
  await page.evaluate(async()=>{
    const {beginOnboardingOperation}=await import('/src/lib/onboardingStore.ts');
    window.oldVisit=beginOnboardingOperation('folder',window.store.getState().activeProjectId);
  });
  await button('上一步').click(); await at('create-project');
  assert.equal(await page.evaluate(()=>window.store.getState().activeProjectId),null);
  await button('稍后继续').click(); await page.reload();
  await button('继续入门引导').click(); await button('我是设计师').click(); await at('create-project');
  assert.equal(await page.evaluate(()=>window.store.getState().activeProjectId),null);
  await next().click(); await at('folder'); await notReady();
  assert.equal(await page.evaluate(()=>window.store.getState().activeProjectId),projectId);
  await page.evaluate(async()=>{
    const {beginOnboardingOperation}=await import('/src/lib/onboardingStore.ts');
    window.oldVisit=beginOnboardingOperation('folder',window.store.getState().activeProjectId);
  });
  await button('上一步').click(); await at('create-project');
  await next().click(); await at('folder');
  await page.evaluate(()=>window.oldVisit()); await notReady();
  assert.equal(await page.evaluate(id=>!!window.store.getState().projects.find(p=>p.id===id).provisional,projectId),false);
  await page.evaluate(()=>{window.cancelPick=true;});
  await pick('导入文件夹'); await notReady();
  await page.evaluate(()=>{window.cancelPick=false;window.wrongFolder=true;});
  await pick('导入文件夹'); await notReady();
  assert.equal(await page.evaluate(()=>window.calls.filter(c=>c.command==='import_folder').length),0);
  await page.evaluate(()=>{window.wrongFolder=false;window.failImport=true;});
  await pick('导入文件夹'); await notReady();
  await page.evaluate(()=>{window.failImport=false;});
  await page.locator('[data-import-trigger]').click();
  await page.waitForTimeout(200); await spotlightContains('[data-tour=import-folder]');
  await page.locator('[data-spotlight-highlight]').waitFor();
  await page.screenshot({path:'.tmp/onboarding-designer-import.png'});
  await page.getByRole('menuitem',{name:'导入文件夹',exact:true}).click();
  await at('source-scope'); await ready();
  await page.waitForTimeout(200); await spotlightContains('.canvas-source-panel');
  assert.equal(await page.getByRole('tab',{name:'项目素材',exact:true}).getAttribute('aria-selected'),'true');
  await page.getByText(/全局素材包含项目素材/).waitFor();
  assert.equal(await page.evaluate(()=>window.calls.some(c=>c.command==='import_files')),false);
  assert.equal(await page.evaluate(()=>window.calls.filter(c=>c.command==='plugin:dialog|open').at(-1).args.options.defaultPath),'C:/fixture');
  await page.screenshot({path:'.tmp/onboarding-designer-scope.png'});
  await button('上一步').click(); await at('folder'); await notReady();
  await next().click(); await at('source-scope'); await ready();
  await next().click(); await at('open-explore'); await notReady();
  await button('探索').click(); await at('explore'); await notReady();
  await page.waitForFunction(()=>window.calls.some(c=>c.command==='open_source_browser'));
  assert.equal(await page.evaluate(()=>window.calls.find(c=>c.command==='open_source_browser').args.url),'https://www.xiaohongshu.com/explore');
  await page.locator('.onboarding-drag-demo').waitFor();
  await page.locator('.canvas-source-expand').waitFor();
  await button('稍后继续').click(); await page.reload();
  await button('继续入门引导').click(); await button('我是设计师').click(); await at('explore');
  await button('打开探索继续采集').click();
  await page.locator('.canvas-source-expand').waitFor();
  await page.setViewportSize({width:1200,height:800});
  await page.waitForTimeout(250);
  assert.equal(await page.locator('.onboarding-spotlight-card').evaluate(el=>{
    const r=el.getBoundingClientRect(), b=document.querySelector('.explore-browser').getBoundingClientRect();
    return r.left>=b.right && r.right<=innerWidth && r.bottom<=innerHeight;
  }),true);
  await page.setViewportSize({width:1600,height:1000}); await page.waitForTimeout(250);
  await page.screenshot({path:'.tmp/onboarding-designer-drag.png'});
  await page.emulateMedia({reducedMotion:'reduce'});
  assert.equal(await page.locator('.demo-cursor').evaluate(el=>getComputedStyle(el).animationName),'none');
  await page.emulateMedia({reducedMotion:'no-preference'});
  async function drop() {
    await page.locator('[data-canvas-stage]').evaluate(el=>{
      const rect=el.getBoundingClientRect(), data=new DataTransfer();
      data.setData('application/x-bowerbird-explorer',JSON.stringify({version:1,imageUrl:'https://fixture.invalid/a.png',pageUrl:'https://fixture.invalid/'}));
      el.dispatchEvent(new DragEvent('drop',{bubbles:true,cancelable:true,dataTransfer:data,clientX:rect.x+160,clientY:rect.y+160}));
    });
  }
  await page.evaluate(()=>{window.failCapture=true;});
  await drop(); await notReady();
  await page.evaluate(()=>{window.failCapture=false;});
  await drop(); await at('expand-source'); await notReady();
  await page.waitForTimeout(200); await spotlightContains('.canvas-workspace');
  const frame=await page.locator('[data-spotlight-highlight]').boundingBox();
  const expand=await page.locator('.canvas-source-expand').boundingBox();
  assert.ok(frame.width < expand.width+10 && frame.height < expand.height+10);
  await page.waitForFunction(()=>window.calls.filter(c=>c.command==='resize_source_browser').at(-1)?.args.dimmed===true);
  await button('收起入门引导').click();
  await page.waitForFunction(()=>window.calls.filter(c=>c.command==='resize_source_browser').at(-1)?.args.dimmed===false);
  await button('展开入门引导').click();
  await page.waitForFunction(()=>window.calls.filter(c=>c.command==='resize_source_browser').at(-1)?.args.dimmed===true);
  await page.screenshot({path:'.tmp/onboarding-designer-expand.png'});
  assert.ok((await page.locator('.onboarding-step-copy').innerText()).includes('该项目中。\n当然'));
  await button('展开画板素材库').click(); await ready();
  await next().click(); await at('activate-composer'); await notReady();
  await page.locator('[data-onboarding-composer] .ProseMirror').click();
  await at('sample-dimensions'); await notReady();
  await button('稍后继续').click();
  await button('继续入门引导').click(); await button('我是设计师').click(); await at('sample-dimensions');
  await page.waitForTimeout(300);
  await spotlightContains('.canvas-source-panel [data-asset-id="existing"]');
  assert.equal(await page.locator('.onboarding-step-copy strong').innerText(),'反推');
  await page.screenshot({path:'.tmp/onboarding-designer-sample.png'});
  await page.locator('.canvas-source-panel [data-asset-id="existing"]').click();
  await at('pick-prompt'); await page.getByRole('group',{name:'可选维度环'}).waitFor(); await notReady();
  await page.waitForFunction(()=>window.calls.filter(c=>c.command==='resize_source_browser').at(-1)?.args.visible===false);
  const ringOpenCount=await page.evaluate(()=>window.calls.filter(c=>['open_source_browser','navigate_source_browser','reload_source_browser'].includes(c.command)).length);
  await spotlightContains('[data-dim="反推提示词"]');
  await page.screenshot({path:'.tmp/onboarding-designer-ring.png'});
  assert.equal(await page.evaluate(()=>window.calls.some(c=>c.command==='codex_describe_asset')),false);
  await at('pick-prompt'); await notReady();
  await page.getByText('请点击选择「反推提示词」维度，将其添加到对话框',{exact:true}).waitFor();
  await button('添加维度 色调').locator('text').click(); await notReady();
  await button('添加维度 反推提示词').locator('text').click(); await ready();
  const editor=page.locator('[data-onboarding-composer] .ProseMirror');
  await editor.locator('[data-keyword][data-source-asset-id="existing"]').filter({hasText:'【反推提示词】'}).waitFor();
  await page.getByText('所选的「反推提示词」维度已经添加到了对话框。你可以继续补充创作需求。',{exact:true}).waitFor();
  await page.locator('.caption-ring-svg').waitFor({state:'hidden'});
  await page.waitForFunction(()=>window.calls.filter(c=>c.command==='resize_source_browser').at(-1)?.args.visible===true);
  await spotlightContains('[data-onboarding-composer]');
  assert.equal(await page.evaluate(()=>window.calls.filter(c=>['open_source_browser','navigate_source_browser','reload_source_browser'].includes(c.command)).length),ringOpenCount,'ring dismissal restores the same webview without navigation');
  await page.screenshot({path:'.tmp/onboarding-designer-prompt-added.png'});
  await next().click(); await at('more-uses'); await ready();
  await page.getByText('这里还有更多使用方法，一定要试试哦！',{exact:true}).waitFor();
  await spotlightContains('.canvas-workspace');
  assert.deepEqual(await page.evaluate(()=>window.lesson.getState().guide.completedRoles),[]);
  assert.equal(await button('完成本次引导').count(),0);
  assert.equal(await page.getByRole('dialog',{name:'入门引导已完成',exact:true}).count(),0);
  assert.equal(await page.locator('[data-tour=explore]').getAttribute('aria-pressed'),'false');
  await page.screenshot({path:'.tmp/onboarding-designer-more-uses.png'});
  await button('上一步').click(); await at('pick-prompt'); await ready();
  await next().click(); await at('more-uses'); await ready();
  await next().click(); await at('ready-to-create'); await ready();
  const completion = page.getByRole('dialog',{name:'入门引导已完成',exact:true});
  await completion.waitFor();
  assert.equal(await page.locator('[data-spotlight-hole]').count(),0);
  await page.waitForFunction(()=>window.calls.some(c=>c.command==='hide_source_browser'));
  await page.getByText('恭喜你，已完成设计师入门引导！',{exact:true}).waitFor();
  assert.equal(await page.locator('.onboarding-brand').evaluate(el=>el.complete && el.naturalWidth>0),true);
  assert.equal(await completion.locator('input[type=email]').count(),0);
  assert.equal(await page.evaluate(()=>window.calls.some(c=>c.command==='cloud_start_wechat_login')),false);
  await page.evaluate(()=>window.store.setState({cloudAuth:{logged_in:false,cloud_available:true}}));
  assert.equal(await page.locator('.onboarding-completion-grid').evaluate(el=>{
    const [left,right]=Array.from(el.children).map(c=>c.getBoundingClientRect()); return right.left>left.right && Math.abs(left.top-right.top)<5;
  }),true);
  await page.waitForTimeout(250);
  await page.screenshot({path:'.tmp/onboarding-designer-finish.png'});
  await page.setViewportSize({width:560,height:720});
  assert.equal(await completion.evaluate(el=>el.scrollWidth<=el.clientWidth),true);
  await page.screenshot({path:'.tmp/onboarding-designer-finish-narrow.png'});
  await page.setViewportSize({width:1600,height:1000});
  await page.evaluate(()=>{window.failWechat=true;});
  await button('使用微信扫码登录').click(); await completion.getByRole('alert').filter({hasText:'模拟扫码登录失败'}).waitFor();
  await page.evaluate(()=>{window.failWechat=false;window.failWechatBrowser=true;});
  await button('使用微信扫码登录').click(); await completion.getByRole('alert').filter({hasText:'模拟浏览器打开失败'}).waitFor();
  await page.evaluate(()=>{window.failWechatBrowser=false;});
  await button('使用微信扫码登录').click();
  await page.getByText('已打开二维码，请用微信扫码确认。',{exact:true}).waitFor();
  assert.equal(await page.evaluate(()=>window.calls.filter(c=>c.command==='plugin:shell|open').at(-1).args.path),'https://open.weixin.qq.com/connect/qrconnect?state=fixture');
  await page.evaluate(()=>window.store.setState({cloudAuth:{logged_in:true,cloud_available:true,display_name:'合成账号'}}));
  await page.getByText('已登录，开始创作吧',{exact:true}).waitFor();
  await button('上一步').click(); await at('more-uses'); await ready();
  await next().click(); await at('ready-to-create'); await ready();
  await button('完成本次引导').click();
  await completion.waitFor({state:'hidden'});
  assert.equal(await page.locator('[data-spotlight-hole]').count(),0);
  assert.equal(await button('完成本次引导').count(),0);
  assert.deepEqual(await page.evaluate(()=>window.lesson.getState().guide.completedRoles),['designer']);
  assert.equal(await page.locator('.onboarding-login-hint').count(),0);
  await page.evaluate(()=>window.store.setState({cloudAuth:{logged_in:false,cloud_available:true}}));
  await page.evaluate(()=>window.lesson.getState().open());
  await button('我是视频编导').click(); await ready(); await next().click();
  await pick('导入图片'); await ready(); await next().click(); await at('script');
  await editor.fill('镜头一：产品居中，镜头缓慢推进。\n镜头二：近景展示包装，保持柔和侧光。');
  await ready(); await next().click(); await at('storyboard'); await notReady();
  await fakeResult('image',1); await ready(); await next().click(); await at('video');
  await fakeResult('image',1); await notReady();
  await fakeResult('video',1); await ready(); await button('完成这条路线').click();
  await button('我是市场运营').click(); await ready(); await next().click();
  await pick('导入图片'); await ready(); await next().click(); await at('collections');
  await page.evaluate(()=>{window.collectionHasAssets=true;window.store.getState().setCollectionPanel('existing-folder');});
  await page.getByRole('dialog',{name:'已有品牌集合',exact:true}).waitFor();
  await ready();
  await page.getByRole('dialog').getByRole('button',{name:'关闭',exact:true}).first().click();
  await next().click(); await at('profile');
  // Isolate the completion hook for saved profile scope; save UI has its own regression.
  await page.evaluate(async()=>{
    const {beginOnboardingOperation}=await import('/src/lib/onboardingStore.ts');
    beginOnboardingOperation('profile',window.store.getState().activeProjectId)({collectionId:'wrong',profileId:'profile'});
  });
  await notReady();
  await page.evaluate(async()=>{
    const {beginOnboardingOperation}=await import('/src/lib/onboardingStore.ts');
    beginOnboardingOperation('profile',window.store.getState().activeProjectId)({collectionId:'existing-folder',profileId:'profile'});
    window.store.setState({visualProfiles:[{id:'profile',name:'测试规范',status:'confirmed',version:1}]});
  });
  await ready(); await next().click(); await at('profile-select');
  await page.getByLabel('品牌视觉规范',{exact:true}).selectOption('profile'); await ready();
  await next().click(); await at('batch');
  await fakeResult('image',2,{visualProfileId:'wrong'}); await notReady();
  await fakeResult('image',1,{visualProfileId:'profile'}); await notReady();
  await fakeResult('image',1,{visualProfileId:'profile'}); await ready();
  await button('完成这条路线').click();
  await page.getByRole('heading',{name:'你已完成所有身份的实操引导',exact:true}).waitFor();
  await button('继续使用').click(); await page.reload();
  assert.equal(await page.locator('.onboarding-resume').count(),0);
  assert.equal(await page.evaluate(()=>window.lesson.getState().guide.completedRoles.length),3);
  await page.evaluate(()=>window.lesson.getState().open()); await button('我是设计师').click();
  await at('create-project'); await button('新建创作').click(); await at('folder');
  await button('稍后继续').click(); await page.locator('.onboarding-resume').waitFor();
  await button('测试登录入口').click(); await page.locator('.onboarding-resume').waitFor({state:'hidden'});
  await page.getByRole('dialog').getByRole('button',{name:'关闭',exact:true}).first().click();
  await page.reload(); await button('继续入门引导').click(); await button('我是设计师').click();
  await at('folder'); await notReady();
  await page.evaluate(async()=>{
    const {beginOnboardingOperation}=await import('/src/lib/onboardingStore.ts');
    const store=window.lesson.getState(), original=store.guide, s=original.sessions.designer;
    const oldCompletion=beginOnboardingOperation('folder',s.projectId);
    const replay={...original,sessions:{...original.sessions,designer:{...s,runId:'new-replay'}}};
    store.setGuide(replay); oldCompletion();
    if (window.lesson.getState().guide.sessions.designer.ready) throw Error('late operation advanced replay');
    store.setGuide(original);
    beginOnboardingOperation('folder','another-project')();
    if (window.lesson.getState().guide.sessions.designer.ready) throw Error('wrong project advanced practice');
  });
  const kept=await page.evaluate(()=>window.lesson.getState().guide.sessions.designer.projectId);
  await page.evaluate(()=>{window.failSave=true;window.store.setState({projectCanvasFlush:async()=>{throw Error('save');}});});
  await button('暂停入门引导').click(); await page.getByRole('alert').filter({hasText:'草稿尚未保存'}).waitFor();
  await button('收起入门引导').click(); await button('跳过入门引导').click();
  assert.equal(await page.locator('.onboarding-lesson,.onboarding-resume').count(),0);
  assert.equal(await page.evaluate(()=>window.lesson.getState().guide.sessions.designer.projectId),kept);
  await page.reload();
  assert.equal(await page.locator('.onboarding-lesson,.onboarding-resume').count(),0);
  await page.evaluate(()=>window.lesson.getState().open());
  await page.setViewportSize({width:560,height:720});
  await page.screenshot({path:'.tmp/onboarding-practice-narrow.png'});
  assert.equal(await page.getByRole('dialog').evaluate(el=>el.scrollWidth<=el.clientWidth),true);
  await page.setViewportSize({width:1600,height:1000});
  await button('我是设计师').click(); await at('folder');
  const late=await page.evaluate(async()=>{
    const {beginOnboardingOperation}=await import('/src/lib/onboardingStore.ts');
    window.lateFolder=beginOnboardingOperation('folder',window.store.getState().activeProjectId);
    return true;
  });
  assert.ok(late);
  await button('跳过此步').click(); await at('source-scope');
  await page.evaluate(()=>window.lateFolder());
  assert.deepEqual(await page.evaluate(()=>window.lesson.getState().guide.sessions.designer.skippedSteps),[1]);
  await button('稍后继续').click(); await page.reload();
  await button('继续入门引导').click(); await button('我是设计师').click(); await at('source-scope');
  await button('跳过此步').click(); await at('open-explore');
  await button('跳过此步').click(); await at('explore');
  await button('跳过此步').click(); await at('expand-source');
  await button('跳过此步').click(); await at('activate-composer');
  await page.evaluate(()=>{window.missingSample=true;});
  await button('跳过此步').click(); await at('sample-dimensions');
  await page.getByText(/未找到带反推数据的示例图/).waitFor(); await notReady();
  await button('跳过此步').click();
  await at('pick-prompt'); await notReady();
  await button('跳过此步').click(); await at('more-uses');
  await button('跳过此步').click(); await at('ready-to-create');
  await button('跳过此步').click();
  await page.evaluate(()=>window.lesson.getState().open());
  await page.getByText('已走完 · 含跳过步骤').waitFor();
  await button('我是设计师').click(); await at('create-project');
  await button('跳过此步').click(); await at('folder');
  assert.equal(await page.evaluate(()=>window.store.getState().activeProjectId),null);
  await button('稍后继续').click(); await page.reload();
  await button('继续入门引导').click(); await button('我是设计师').click(); await at('folder');
  await button('新建创作').click(); await page.locator('.canvas-workspace[aria-busy="false"]').waitFor();
  await at('folder'); await notReady();
  assert.ok(await page.evaluate(()=>window.lesson.getState().guide.sessions.designer.projectId));
  assert.deepEqual(errors,[]);
  console.log('PASS designer eleven-step spotlight practice, final canvas hint, back/reload, prompt selection and completion modal with WeChat-only login, per-step skips and sample dimension ring, starter folder and capture failure gates, native browser URL, drag demo, all roles, pause/reload/skip and modal/narrow layout.');
} catch(error) {
  await mkdir('.tmp',{recursive:true}); await page.screenshot({path:'.tmp/onboarding-practice-failure.png'});
  console.error(await page.evaluate(()=>({guide:window.lesson?.getState().guide,text:document.body.innerText.slice(-3500),calls:window.calls?.slice(-10)})));
  console.error(errors); throw error;
} finally { await browser.close(); await server.close(); }
