const { chromium } = await import(process.env.BOWERBIRD_PLAYWRIGHT_MODULE || 'playwright');
import assert from 'node:assert/strict';
import { mkdir } from 'node:fs/promises';
await mkdir('.tmp', { recursive: true });
const browser=await chromium.launch({channel:'chrome',headless:true});
const page=await browser.newPage({viewport:{width:1100,height:850}});
const errors=[];page.on('pageerror',e=>errors.push(e.message));
await page.goto(`${process.env.BOWERBIRD_UI_TEST_URL || 'http://127.0.0.1:1437'}/scripts/fixtures/project-deletion/preview.html`);
await page.getByRole('button',{name:'删除测试项目'}).click();
const box=page.getByRole('checkbox');
assert.equal(await box.isChecked(),false);
await page.screenshot({path:'.tmp/project-delete-default.png'});
await box.check();
await page.getByRole('button',{name:'取消',exact:true}).click();
assert.equal(await page.evaluate(()=>window.calls.filter(c=>c.command==='delete_project').length),0);
await page.getByRole('button',{name:'删除测试项目'}).click();
assert.equal(await box.isChecked(),false);
await page.getByRole('button',{name:'删除项目，保留素材',exact:true}).click();
await page.waitForFunction(()=>window.calls.some(c=>c.command==='delete_project'));
assert.equal(await page.evaluate(()=>window.calls.find(c=>c.command==='delete_project').args.mode),'keep');
await page.evaluate(()=>{window.reset();window.calls=[];});
await page.getByRole('button',{name:'删除测试项目'}).click();
await box.check();
await page.screenshot({path:'.tmp/project-delete-physical.png'});
await page.getByRole('button',{name:'删除项目并永久删除文件',exact:true}).click();
await page.waitForFunction(()=>window.calls.some(c=>c.command==='delete_project'));
assert.deepEqual(await page.evaluate(()=>window.calls.find(c=>c.command==='delete_project').args),{projectId:'p',mode:'delete_exclusive',confirmation:'test-confirmation'});
await page.evaluate(()=>{window.reset();window.calls=[];window.failure=true;});
await page.getByRole('button',{name:'删除测试项目'}).click();await box.check();
await page.getByRole('button',{name:'删除项目并永久删除文件',exact:true}).click();
await page.waitForFunction(()=>window.notices.at(-1)?.tone==='error');
assert.match(await page.locator('#notice').innerText(),/重新打开删除确认/);
await page.evaluate(()=>{window.reset();window.calls=[];window.failure=false;window.running=1;});
await page.getByRole('button',{name:'删除测试项目'}).click();
assert.equal(await page.getByRole('button',{name:'仍有未完成任务'}).isDisabled(),true);
await page.keyboard.press('Escape');
assert.equal(await page.evaluate(()=>window.calls.filter(c=>c.command==='delete_project').length),0);
await page.evaluate(()=>{window.reset();window.running=0;window.pending=true;});
await page.getByRole('button',{name:'删除测试项目'}).click();await box.check();
await page.getByRole('button',{name:'删除项目并永久删除文件',exact:true}).click();
await page.waitForFunction(()=>window.notices.at(-1)?.message.includes('清理尚未完成'));
assert.equal(await page.evaluate(()=>window.notices.at(-1).tone),'error');
await page.evaluate(()=>{window.reset();window.calls=[];window.pending=false;});
await page.setViewportSize({width:420,height:760});
await page.getByRole('button',{name:'删除测试项目'}).click();await box.check();
await page.screenshot({path:'.tmp/project-delete-narrow.png'});
assert.equal(await page.locator('.app-modal').evaluate(e=>e.scrollWidth>e.clientWidth),false);
const modal=await page.locator('.app-modal').boundingBox();assert.ok(modal.x>=0 && modal.x+modal.width<=420);
await page.keyboard.press('Escape');
await page.evaluate(()=>{window.reset();window.provisional();window.calls=[];});
await page.getByRole('button',{name:'删除测试项目'}).click();
assert.equal(await page.getByRole('checkbox').count(),0);
await page.getByRole('button',{name:'丢弃项目',exact:true}).click();
assert.equal(await page.evaluate(()=>window.calls.filter(c=>['delete_project','project_delete_impact'].includes(c.command)).length),0);
assert.deepEqual(errors,[]);
console.log('PASS: default keep, opt-in token, reset, cancel, Escape, running, failure notice, pending cleanup, narrow layout');
await browser.close();
