import assert from "node:assert/strict";
import { mkdir } from "node:fs/promises";
import { createServer } from "vite";
const { chromium } = await import(process.env.BOWERBIRD_PLAYWRIGHT_MODULE || "playwright");
const server = await createServer({ server: { host: "127.0.0.1", port: 1439, strictPort: true } });
await server.listen();
const browser = await chromium.launch({ channel: "chrome", headless: true });
const page = await browser.newPage({ viewport: { width: 1280, height: 1000 } });
const errors = [];
page.on("pageerror", (error) => errors.push(error.message));
const base = "http://127.0.0.1:1439/scripts/fixtures/project-rename/preview.html";
const dialog = page.getByRole("dialog", { name: "重命名项目", exact: true });
const input = dialog.getByRole("textbox", { name: "项目名称" });
async function open(target) {
  await target.click({ button: "right" });
  await page.getByRole("menuitem", { name: "重命名", exact: true }).click();
  await input.waitFor();
}
async function renameCalls() { return page.evaluate(() => window.calls.filter(c => c.command === "project_canvas_rename").length); }
try {
  await page.goto(base);
  await page.waitForFunction(() => window.fixtureStore?.getState().projectCanvasRename && document.querySelector(".canvas-board-title")?.value === "测试项目");
  await open(page.locator(".project-name"));
  assert.equal(await input.inputValue(), "测试项目");
  await input.fill("   ");
  assert.equal(await dialog.getByRole("button", { name: "保存名称" }).isDisabled(), true);
  await input.press("Enter");
  assert.equal(await renameCalls(), 0);
  await input.fill("取消的名字");
  await dialog.getByRole("button", { name: "取消", exact: true }).click();
  assert.equal(await renameCalls(), 0);
  await open(page.locator(".library-project-folder"));
  await input.fill("输入法名称");
  await input.dispatchEvent("compositionstart");
  await input.dispatchEvent("keydown", { key: "Enter", isComposing: true, bubbles: true });
  await input.dispatchEvent("keydown", { key: "Escape", isComposing: true, bubbles: true });
  assert.equal(await dialog.count(), 1);
  assert.equal(await renameCalls(), 0);
  await input.dispatchEvent("compositionend");
  await input.dispatchEvent("keydown", { key: "Escape", keyCode: 229, bubbles: true });
  assert.equal(await dialog.count(), 1);
  await input.press("Escape");
  assert.equal(await dialog.count(), 0);
  await open(page.locator(".library-project-folder"));
  await input.fill("  新名称  ");
  await input.press("Enter");
  await dialog.waitFor({ state: "detached" });
  assert.equal(await page.locator(".project-name").innerText(), "新名称");
  assert.equal(await page.locator(".library-project-folder-title strong").innerText(), "新名称");
  assert.equal(await page.locator(".canvas-board-title").inputValue(), "新名称");
  assert.equal(await page.evaluate(() => window.persistedProject().title_source), "manual");
  await page.locator(".library-project-folder").click();
  await open(page.locator(".library-project-frame header"));
  assert.equal(await input.inputValue(), "新名称");
  await input.fill("重试名称");
  await page.evaluate(() => { window.failure = true; });
  await dialog.getByRole("button", { name: "保存名称" }).click();
  await dialog.getByRole("alert").waitFor();
  assert.match(await dialog.getByRole("alert").innerText(), /合成写入失败/);
  assert.equal(await input.inputValue(), "重试名称");
  assert.equal(await page.locator(".canvas-board-title").inputValue(), "新名称");
  await mkdir(".tmp", { recursive: true });
  await page.screenshot({ path: ".tmp/project-rename-failure.png" });
  await page.evaluate(() => { window.failure = false; });
  await dialog.getByRole("button", { name: "保存名称" }).click();
  await dialog.waitFor({ state: "detached" });
  assert.equal(await page.locator(".library-project-title-button span").innerText(), "重试名称");
  assert.equal(await page.locator(".project-name").innerText(), "重试名称");
  assert.equal(await page.locator(".canvas-board-title").inputValue(), "重试名称");
  await page.locator(".project-name").click({ button: "right" });
  assert.equal(await page.getByRole("menuitem", { name: "更新项目文件" }).isDisabled(), true);
  await page.getByRole("menuitem", { name: "删除项目 · 素材保留" }).click();
  const checkbox = page.getByRole("checkbox");
  await checkbox.waitFor();
  assert.equal(await checkbox.isChecked(), false);
  await page.keyboard.press("Escape");
  await page.goto(`${base}?inactive`);
  await open(page.locator(".project-name"));
  await input.fill("非当前项目");
  await input.press("Enter");
  await dialog.waitFor({ state: "detached" });
  assert.equal(await page.locator(".project-name").innerText(), "非当前项目");
  await open(page.locator(".project-name"));
  await page.evaluate(() => { window.missing = true; });
  await input.fill("已删除");
  await input.press("Enter");
  await dialog.getByRole("alert").waitFor();
  assert.match(await dialog.getByRole("alert").innerText(), /已不存在/);
  await page.goto(`${base}?provisional`);
  await open(page.locator(".project-name"));
  await input.fill("已保存项目");
  await input.press("Enter");
  await dialog.waitFor({ state: "detached" });
  assert.equal(await page.locator(".canvas-board-title").inputValue(), "已保存项目");
  const project = await page.evaluate(() => window.persistedProject());
  assert.equal(project.id, "p");
  assert.equal(project.title_source, "manual");
  assert.equal(project.provisional, false);
  await page.goto(`${base}?inactive&rail`);
  await open(page.getByRole("button", { name: "切换到项目 测试项目", exact: true }));
  await input.fill("收起侧栏改名");
  await input.press("Enter");
  await dialog.waitFor({ state: "detached" });
  assert.equal(await page.getByRole("button", { name: "切换到项目 收起侧栏改名", exact: true }).count(), 1);
  assert.equal(await page.locator(".library-project-folder-title strong").innerText(), "收起侧栏改名");
  assert.deepEqual(errors, []);
  console.log("PASS: real project menu/sidebar/home/canvas; blank/cancel/Escape/IME; success sync/manual title; failure retry/missing; inactive/provisional; deletion opt-in retained");
} finally {
  await browser.close();
  await server.close();
}
