import assert from "node:assert/strict";
import { mkdir } from "node:fs/promises";
import { createServer } from "vite";
import { chromium } from "../../html-renderer/node_modules/playwright/index.mjs";

const server = await createServer({ server: { host: "127.0.0.1", port: 1596, strictPort: true, hmr: false, watch: null } });
await server.listen();
const browser = await chromium.launch({ channel: "chrome", headless: true });
const page = await browser.newPage({ viewport: { width: 1440, height: 1000 } });
const errors = [];
page.on("pageerror", error => errors.push(error.message));
const sidebar = page.locator(".app-sidebar");
const avatar = page.locator('[data-tour="sidebar-account"]');
const hidden = () => sidebar.evaluate(el => el.classList.contains("is-auto-hidden"));
const settle = () => page.waitForTimeout(2300);
try {
  await page.goto("http://127.0.0.1:1596/scripts/fixtures/onboarding/preview.html");
  await page.getByRole("button", { name: "跳过入门引导", exact: true }).click();
  await page.evaluate(() => {
    window.store.setState({ activeProjectId: null, boardOpen: false, cloudAuth: { logged_in: true, display_name: "测试用户", avatar_url: 'data:image/svg+xml,<svg xmlns="http://www.w3.org/2000/svg" width="32" height="32"><rect width="32" height="32" fill="cornflowerblue"/></svg>' } });
  });
  await page.getByRole("button", { name: "收起侧栏", exact: true }).click();
  assert.equal(await avatar.locator("img").count(), 1);
  await avatar.click();
  for (const name of ["升级账号", "设置", "登出"]) assert.equal(await page.getByRole("menuitem", { name: new RegExp(`^${name}`) }).count(), 1, name);
  await page.getByRole("menuitem", { name: /^设置/ }).click();
  await page.getByRole("dialog").waitFor();
  await page.keyboard.press("Escape");
  await page.evaluate(() => window.store.setState({ cloudAuth: { logged_in: false } }));
  await avatar.click();
  assert.equal(await page.getByRole("menuitem", { name: "登录 Bowerbird 账号", exact: true }).count(), 1);
  await page.keyboard.press("Escape");
  await page.getByRole("button", { name: "展开侧栏", exact: true }).click();
  await page.mouse.move(700, 300);
  await page.evaluate(() => { document.activeElement?.blur(); window.store.setState({ activeProjectId: "p" }); });
  assert.equal(await hidden(), false);
  await page.waitForTimeout(900);
  assert.equal(await hidden(), false, "show the sidebar before two seconds elapse");
  const beforeHide = await page.locator(".canvas-workspace").boundingBox();
  await page.waitForFunction(() => document.querySelector(".app-sidebar.is-auto-hidden"));
  await page.waitForFunction(() => document.querySelector(".app-sidebar").getBoundingClientRect().right <= 1);
  await page.waitForFunction(() => document.querySelector(".app-sidebar-host").getBoundingClientRect().width <= 4.1);
  const afterHide = await page.locator(".canvas-workspace").boundingBox();
  assert.ok(Math.abs(beforeHide.x - afterHide.x - 46) < 1, "workspace fills the released sidebar width");
  assert.ok(Math.abs(afterHide.width - beforeHide.width - 46) < 1, "canvas gains the released width");
  await page.mouse.move(2, 500);
  await page.waitForFunction(() => !document.querySelector(".app-sidebar.is-auto-hidden"));
  await settle();
  assert.equal(await hidden(), false, "hover keeps the sidebar visible");
  await avatar.click();
  await page.mouse.move(700, 300);
  await settle();
  assert.equal(await hidden(), false, "account menu stays usable outside the narrow rail");
  await page.getByRole("menuitem", { name: /^设置/ }).click();
  await settle();
  assert.equal(await hidden(), false);
  const modal = await page.getByRole("dialog").boundingBox();
  assert.equal(modal.width, 1440, "settings remains a full-window dialog");
  await page.keyboard.press("Escape");
  await page.mouse.click(700, 300);
  await page.waitForFunction(() => document.querySelector(".app-sidebar.is-auto-hidden"));
  await page.mouse.move(2, 500);
  await page.getByRole("button", { name: "展开侧栏", exact: true }).click();
  const resize = await page.getByRole("separator", { name: "调整侧栏宽度" }).boundingBox();
  await page.mouse.move(resize.x + resize.width / 2, resize.y + 180);
  await page.mouse.down();
  await page.mouse.move(resize.x + resize.width / 2 + 60, resize.y + 180, { steps: 6 });
  await page.mouse.up();
  assert.ok((await sidebar.boundingBox()).width > 198, "sidebar resizing still uses the workspace width");
  await page.waitForFunction(() => Math.abs(document.querySelector(".app-sidebar-host").getBoundingClientRect().width - document.querySelector(".app-sidebar").getBoundingClientRect().width) < 1);
  await mkdir(".tmp/sidebar", { recursive: true });
  await page.screenshot({ path: ".tmp/sidebar/expanded.png" });
  await page.mouse.click(700, 300);
  await page.waitForFunction(() => document.querySelector(".app-sidebar.is-auto-hidden"));
  await page.waitForFunction(() => document.querySelector(".app-sidebar-host").getBoundingClientRect().width <= 4.1);
  assert.ok((await page.locator(".canvas-workspace").boundingBox()).x <= 5, "expanded sidebar also releases its full width");
  // Keyboard navigation to an off-screen control must reveal it too.
  await page.getByRole("button", { name: "显示侧栏", exact: true }).focus();
  await page.waitForFunction(() => document.activeElement?.getAttribute("aria-label") === "收起侧栏");
  assert.equal(await hidden(), false);
  await settle();
  assert.equal(await hidden(), false);
  await page.evaluate(() => window.store.setState({ activeProjectId: null }));
  await page.getByRole("button", { name: "收起侧栏", exact: true }).waitFor();
  await page.mouse.click(700, 300);
  await settle();
  assert.equal(await sidebar.evaluate(el => el.classList.contains("is-auto-hide")), false);
  assert.equal(await page.evaluate(() => localStorage.getItem("bowerbird.sidebarCollapsed")), "0");
  await page.getByRole("button", { name: "收起侧栏", exact: true }).click();
  await avatar.click();
  await page.screenshot({ path: ".tmp/sidebar/collapsed-account.png" });
  assert.deepEqual(errors, []);
  console.log("PASS: compact avatar and account/settings menu; delayed hide, hover reveal, menu/modal hold, keyboard access, expanded drawer, restored library preference");
} finally {
  await browser.close();
  await server.close();
}
